/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.OpenProblem.Util.Complexity.Definitions.UnitCostRAMMachine

/-!
# Minimal strict cost-analysis core

This module is the smallest problem-facing layer of the unit-cost RAM
framework.  A user may state a readable cost formula, but that formula is
accepted only together with a proof that it bounds the operation count of the
fixed-encoding instruction-level execution.

The module performs no source-code analysis and chooses no representation.
Input and output encodings remain parameters fixed before the implementation
witness.
-/

namespace EconCSLib.OpenProblem.UnitCostRAM.StrictCostCore

universe u v

noncomputable section

/-- A short name for the strict, fixed-representation implementation whose
actual execution is counted by the RAM interpreter. -/
abbrev Implementation
    {Input : Type u} {Output : Input → Type v}
    (inputEncoding : Encoding Input)
    (outputEncoding : DependentEncoding Output)
    (function : (input : Input) → Output input) :=
  FixedEncodingRAMImplementation inputEncoding outputEncoding function

/-- The exact local-step cost generated by the interpreter on one input. -/
def executionCost
    {Input : Type u} {Output : Input → Type v}
    {inputEncoding : Encoding Input}
    {outputEncoding : DependentEncoding Output}
    {function : (input : Input) → Output input}
    (implementation : Implementation inputEncoding outputEncoding function)
    (input : Input) : ℕ :=
  implementation.operationCount input

/-- A user formula describes the exact interpreter cost on every input. -/
def HasExactCost
    {Input : Type u} {Output : Input → Type v}
    {inputEncoding : Encoding Input}
    {outputEncoding : DependentEncoding Output}
    {function : (input : Input) → Output input}
    (implementation : Implementation inputEncoding outputEncoding function)
    (formula : Input → ℕ) : Prop :=
  ∀ input, executionCost implementation input = formula input

/-- A user formula is a sound pointwise upper bound for the interpreter cost.
This is the usual interface for worst-case analysis with branches or early
termination. -/
def HasCostBound
    {Input : Type u} {Output : Input → Type v}
    {inputEncoding : Encoding Input}
    {outputEncoding : DependentEncoding Output}
    {function : (input : Input) → Output input}
    (implementation : Implementation inputEncoding outputEncoding function)
    (bound : Input → ℕ) : Prop :=
  ∀ input, executionCost implementation input ≤ bound input

/-- A displayed cost formula has one global natural-coefficient polynomial
majorant in the fixed encoded-input size. -/
def IsPolynomialFormula
    {Input : Type u}
    (inputEncoding : Encoding Input) (formula : Input → ℕ) : Prop :=
  IsPolyBound inputEncoding.size formula

/-- The selected displayed formula both bounds the exact execution and is
polynomially bounded. -/
def IsPolynomialTimeVia
    {Input : Type u} {Output : Input → Type v}
    {inputEncoding : Encoding Input}
    {outputEncoding : DependentEncoding Output}
    {function : (input : Input) → Output input}
    (implementation : Implementation inputEncoding outputEncoding function)
    (bound : Input → ℕ) : Prop :=
  HasCostBound implementation bound ∧
    IsPolynomialFormula inputEncoding bound

/-- The strict implementation admits some explicit sound polynomial cost
formula.  The formula is a proof witness; the actual cost remains the
interpreter-generated `executionCost`. -/
def IsPolynomialTime
    {Input : Type u} {Output : Input → Type v}
    {inputEncoding : Encoding Input}
    {outputEncoding : DependentEncoding Output}
    {function : (input : Input) → Output input}
    (implementation : Implementation inputEncoding outputEncoding function) :
    Prop :=
  ∃ bound : Input → ℕ, IsPolynomialTimeVia implementation bound

end

end EconCSLib.OpenProblem.UnitCostRAM.StrictCostCore
