/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.Foundation.Utility.Lottery
import EconCSLib.MechanismDesign.Auction.Transfer
import EconCSLib.OpenProblem.SubmodularWelfareDemandOracle
import EconCSLib.OpenProblem.Util.Answer
import EconCSLib.OpenProblem.Util.Complexity
import EconCSLib.OpenProblem.Util.PPAD
import EconCSLib.SocialChoice.FairDivision.Divisible.Instance
import EconCSLib.SocialChoice.FairDivision.Indivisible.Instance
import EconCSLib.SocialChoice.FairDivision.Indivisible.MMS
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Combinatorics.Matroid.Basic
import Mathlib.Combinatorics.SimpleGraph.Basic
import Mathlib.MeasureTheory.Constructions.Pi
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# Common interfaces for the EconCS Bench open problems

This module contains the small amount of vocabulary used across the translated
Markdown problems in `EconCSLib/OpenProblem`.  Existing EconCSLib definitions
are reused wherever their typeclass assumptions and interfaces match.  In
particular, bundle valuations and demand oracles come from
`OpenProblem.SubmodularWelfareDemandOracle`, fair-division allocations come
from `SocialChoice.FairDivision.Indivisible`, the homogeneous bundle-mechanism
wrapper below converts to `MechanismDesign.Auction.Transfer`, and finite
distributions use `Lottery`.

The shared complexity module now provides a unit-cost RAM accounting semantics
for cost-annotated implementations of arbitrary dependent functions.  A few
older list-only hooks remain temporarily for problem files that have not yet
been migrated to actual functions or counters.
-/

open scoped BigOperators

namespace EconCSLib
namespace OpenProblem
namespace EconCSBench

/-! ## Finite probability distributions -/

/-- The uniform lottery on a finite nonempty type. -/
noncomputable def uniformLottery (α : Type*) [Fintype α] [Nonempty α] : Lottery ℝ α :=
  ⟨fun _ => (1 : ℝ) / Fintype.card α,
    fun _ => div_nonneg zero_le_one (Nat.cast_nonneg _),
    by
      have hcard : (0 : ℝ) < Fintype.card α := by
        exact_mod_cast Fintype.card_pos
      rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul]
      field_simp⟩

/-! ## Bundle valuations not already present in EconCSLib -/

/-- A monotone bundle valuation satisfying subadditivity. -/
structure SubadditiveBundleValuation
    {G : Type*} [DecidableEq G] (M : Finset G)
    extends MonotoneBundleValuation M where
  /-- The value of a union is at most the sum of the separate values. -/
  subadditive :
    ∀ S T : BundleAllocation M,
      val ⟨S.1 ∪ T.1, by
        intro g hg
        simp only [Finset.mem_union] at hg
        exact hg.elim (fun h => S.2 h) (fun h => T.2 h)⟩ ≤ val S + val T

/-- An XOS valuation: a finite family of nonnegative additive clauses exists
whose pointwise maximum is the valuation.  The representation witness lives in
`Prop`, so two reports with the same value function cannot be distinguished by
inspecting different choices of additive clauses. -/
structure XOSBundleValuation
    {G : Type*} [DecidableEq G] (M : Finset G)
    extends BundleValuation M where
  /-- Existence of a finite nonempty XOS representation. -/
  isXOS :
    ∃ clauseCount : ℕ, 0 < clauseCount ∧
      ∃ clauseWeight : Fin clauseCount → BundlePriceVector M,
        (∀ c g, 0 ≤ clauseWeight c g) ∧
          ∀ S : BundleAllocation M,
            ∃ c : Fin clauseCount,
              val S =
                  S.1.attach.sum
                    (fun g => clauseWeight c ⟨g.1, S.2 g.2⟩) ∧
                ∀ d : Fin clauseCount,
                  S.1.attach.sum
                      (fun g => clauseWeight d ⟨g.1, S.2 g.2⟩) ≤
                    val S

/-- The measurable structure generated by the finitely many bundle-value
coordinates.  This is the natural finite-dimensional Borel structure and, in
particular, supports ordinary continuous as well as discrete valuation priors. -/
instance instMeasurableSpaceSubadditiveBundleValuation
    {G : Type*} [DecidableEq G] {M : Finset G} :
    MeasurableSpace (SubadditiveBundleValuation M) :=
  MeasurableSpace.comap
    (fun v : SubadditiveBundleValuation M =>
      (v.val : BundleAllocation M → ℝ))
    inferInstance

instance instMeasurableSpaceXOSBundleValuation
    {G : Type*} [DecidableEq G] {M : Finset G} :
    MeasurableSpace (XOSBundleValuation M) :=
  MeasurableSpace.comap
    (fun v : XOSBundleValuation M =>
      (v.val : BundleAllocation M → ℝ))
    inferInstance

/-! ## Shared allocation and welfare vocabulary -/

/-- A disjoint bundle allocation exhausts the ground set. -/
def IsCompleteBundleAllocation
    {I G : Type*} [DecidableEq G] {M : Finset G}
    (A : BundlePartitionAllocation I M) : Prop :=
  ∀ g ∈ M, ∃ i : I, g ∈ (A.1 i).1

/-- Social welfare for an arbitrary profile of bundle-value functions. -/
noncomputable def bundleSocialWelfare
    {I G : Type*} [Fintype I] [DecidableEq G] {M : Finset G}
    (v : I → BundleAllocation M → ℝ)
    (A : BundlePartitionAllocation I M) : ℝ :=
  ∑ i, v i (A.1 i)

/-- Offline optimal welfare over all disjoint (possibly partial) allocations. -/
noncomputable def bundleOPT
    {I G : Type*} [Fintype I] [DecidableEq G] {M : Finset G}
    (v : I → BundleAllocation M → ℝ) : ℝ :=
  ⨆ A : BundlePartitionAllocation I M, bundleSocialWelfare v A

/-! ## Posted prices and demand choices -/

/-- Quasi-linear utility of a bundle for an arbitrary value function. -/
def netBundleUtility
    {G : Type*} [DecidableEq G] {M : Finset G}
    (v : BundleAllocation M → ℝ) (p : BundlePriceVector M)
    (S : BundleAllocation M) : ℝ :=
  v S - S.1.attach.sum (fun g => p ⟨g.1, S.2 g.2⟩)

/-- A bundle maximizes quasi-linear utility among the bundles contained in the
currently available item set. -/
def IsDemandBundle
    {G : Type*} [DecidableEq G] {M : Finset G}
    (v : BundleAllocation M → ℝ) (p : BundlePriceVector M)
    (available : Finset G) (S : BundleAllocation M) : Prop :=
  S.1 ⊆ available ∧
    ∀ T : BundleAllocation M, T.1 ⊆ available →
      netBundleUtility v p T ≤ netBundleUtility v p S

/-! ## Direct combinatorial mechanisms -/

/-- A homogeneous-report specialization of a deterministic direct mechanism
for bundle allocation with payments.  The dedicated field names preserve the
benchmark API; `toMechanismWithTransfers` supplies interoperability with the
library's general transfer-mechanism structure. -/
structure DeterministicBundleMechanism
    (I Report : Type*) {G : Type*} [DecidableEq G] (M : Finset G) where
  /-- Allocation selected from the report profile. -/
  allocation : (I → Report) → BundlePartitionAllocation I M
  /-- Payment charged to every agent. -/
  payment : (I → Report) → I → ℝ

/-- View the benchmark's homogeneous-report bundle mechanism through the
library's general transfer-mechanism interface. -/
def DeterministicBundleMechanism.toMechanismWithTransfers
    {I Report G : Type*} [DecidableEq G] {M : Finset G}
    (mech : DeterministicBundleMechanism I Report M) :
    MechanismWithTransfers I (fun _ => Report)
      (BundlePartitionAllocation I M) ℝ where
  allocationRule := mech.allocation
  paymentRule := mech.payment

/-- Dominant-strategy truthfulness for a deterministic bundle mechanism. -/
def DeterministicBundleMechanism.IsDSIC
    {I Report G : Type*} [DecidableEq I] [DecidableEq G] {M : Finset G}
    (mech : DeterministicBundleMechanism I Report M)
    (value : Report → BundleAllocation M → ℝ) : Prop :=
  ∀ (truth : I → Report) (i : I) (misreport : Report),
    value (truth i) ((mech.allocation truth).1 i) - mech.payment truth i ≥
      value (truth i)
          ((mech.allocation (Function.update truth i misreport)).1 i) -
        mech.payment (Function.update truth i misreport) i

/-- Ex-post individual rationality for a deterministic bundle mechanism. -/
def DeterministicBundleMechanism.IsIR
    {I Report G : Type*} [DecidableEq G] {M : Finset G}
    (mech : DeterministicBundleMechanism I Report M)
    (value : Report → BundleAllocation M → ℝ) : Prop :=
  ∀ (truth : I → Report) (i : I),
    0 ≤ value (truth i) ((mech.allocation truth).1 i) - mech.payment truth i

/-! ## Partial fair allocations, approximation, and charity -/

/-- A partial indivisible allocation uses only goods from `allGoods` and gives
distinct agents disjoint bundles.  This interface deliberately needs neither a
finite ambient goods type nor decidable equality on agents, assumptions imposed
by the older specialized `EFXSmallGoods.IsPartialAllocation` declaration. -/
structure IsPartialIndivisibleAllocation
    {N G : Type*} [DecidableEq G]
    (allGoods : Finset G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Prop where
  /-- Allocated bundles are pairwise disjoint. -/
  disjoint : ∀ i j : N, i ≠ j → Disjoint (A i) (A j)
  /-- Every allocated good belongs to the instance. -/
  subset_goods : ∀ i : N, A i ⊆ allGoods

/-- Goods left unallocated by a partial allocation. -/
def charity
    {N G : Type*} [Fintype N] [DecidableEq G]
    (allGoods : Finset G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Finset G :=
  allGoods \ Finset.univ.biUnion A

/-- `α`-EFX for goods. -/
def IsAlphaEFXGoods
    {N G : Type*} [DecidableEq G]
    (α : ℝ) (v : SocialChoice.FairDivision.Indivisible.Valuation N G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Prop :=
  ∀ i j : N, i ≠ j → ∀ g ∈ A j,
    α * v.val i (A j \ {g}) ≤ v.val i (A i)

/-- Standard `α`-EFX for chores, using approximation factors `α ≥ 1`:
deleting any chore from the envious agent's own bundle leaves cost at most
`α` times the other agent's cost. Thus `α = 1` is exact EFX and larger
values are weaker guarantees. -/
def IsAlphaEFXChores
    {N G : Type*} [DecidableEq G]
    (α : ℝ) (cost : SocialChoice.FairDivision.Indivisible.Valuation N G)
    (A : SocialChoice.FairDivision.Indivisible.Allocation N G) : Prop :=
  ∀ i j : N, i ≠ j → ∀ g ∈ A i,
    cost.val i (A i \ {g}) ≤ α * cost.val i (A j)

end EconCSBench
end OpenProblem
end EconCSLib
