/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.Foundation.Utility.Lottery
import EconCSLib.OpenProblem.Util.AlgorithmCost
import EconCSLib.OpenProblem.Util.SizeGrowth
import EconCSLib.OpenProblem.Util.SourceCost
import EconCSLib.OpenProblem.Util.StaticComplexity
import EconCSLib.OpenProblem.Util.UnitCostRAM
import EconCSLib.OpenProblem.Util.UnitCostRAMMachine
import Mathlib.Data.Real.Basic
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# Complexity interfaces for EconCS Bench

`UnitCostRAM` provides the shared compositional accounting semantics and
`UnitCostRAMMachine` provides the instruction-enforced semantics.  The
declarations in this module are problem-facing wrappers for ordinary
functions, dependent functions, promise problems, search relations,
structured algorithms, randomized/oracle executions, and explicit resource
counters.

Every polynomial predicate means only that *some* natural constants
`coefficient` and `exponent` give a uniform upper bound.  It neither exposes
nor optimizes those constants.  A list of nonnegative size parameters is
aggregated by addition, which is equivalent to the usual multivariate
polynomial convention up to changing the hidden constants and exponent.
When named variables matter, `MultivariatePolynomialCostBound` instead uses
Mathlib's genuine `MvPolynomial`; the library proves the two conventions
equivalent for every fixed finite parameter family.

`RAMCostedImplementation` is a trusted instrumentation interface: it is useful
inside proofs, but by itself cannot define a complexity class because
`Cost.pure`/`Cost.map` can conceal Lean computation.  New polynomial-time and
polynomial-reduction statements should instead use a fixed input/output
encoding together with `StrictRAMComputableInPolyTime`,
`StrictRAMSearchableInPolyTime`, or the strict resource predicates below.
Polynomial bounds on structural query/communication counters remain valid
when the counter is generated by the program/protocol syntax itself.  Random
seeds, legal oracle implementations, and adversarial tie-breaking rules should
use uniform variants, so the hidden polynomial cannot depend on the auxiliary
choice.

For a family of algorithms indexed by the problem domain or an external
parameter, use the family-level declarations below.  Their coefficient and
exponent are chosen *before* the algorithm index, preventing a nonuniform
family from choosing a different polynomial for every input size.

There are deliberately no list-only propositions of the form
`PolynomialTime [n, m]`: every complexity assertion below mentions an actual
instrumented program, protocol, reduction, or resource counter.

The specialized interfaces follow standard distinctions in the literature:
Yao's distributional model for randomized/communication complexity, the
private-input protocol viewpoint used in communication complexity, Tarjan's
potential method for amortized analysis, and the work--span model for
fork--join parallelism.  `PPAD.lean` separately instantiates the explicit
polynomial-reduction interface with succinct End-of-Line.
-/

namespace EconCSLib
namespace OpenProblem
namespace EconCSBench

universe u v w

open Filter Asymptotics

/-- The unit-cost RAM computation wrapper used by the benchmark API. -/
abbrev RAMCost := UnitCostRAM.Cost

/-- Trusted `CostM` instrumentation of an arbitrary dependent function.
This is a compositional proof object, not an instruction-enforced
polynomial-time certificate. -/
abbrev RAMCostedImplementation
    {Input : Type u} {Output : Input → Type v}
    (function : (input : Input) → Output input) :=
  UnitCostRAM.CostedImplementation function

/-- A cost-annotated implementation required to be correct only on a
promise. -/
abbrev RAMCostedImplementationOn
    {Input : Type u} {Output : Input → Type v}
    (valid : Input → Prop)
    (function : (input : Input) → Output input) :=
  UnitCostRAM.CostedImplementationOn valid function

/-- A cost-annotated solver for a dependent search relation. -/
abbrev RAMCostedSearchImplementation
    {Input : Type u} {Output : Input → Type v}
    (solution : (input : Input) → Output input → Prop) :=
  UnitCostRAM.CostedSearchImplementation solution

/-- A cost-annotated implementation parameterized by a seed, oracle, or
adversarial choice. -/
abbrev RAMCostedImplementationWithChoice
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (function : (input : Input) →
      (choice : Choice input) → Output input choice) :=
  UnitCostRAM.CostedImplementationWithChoice function

/-- Explicit checked majorant for the size of the value returned by a
dependent function.  This is the size-growth component needed for sound
sequential composition of polynomial-time implementations. -/
abbrev RAMOutputSizeCertificate
    {Input : Type u} {Output : Input → Type v}
    (outputSize : (input : Input) → Output input → ℕ)
    (function : (input : Input) → Output input) :=
  UnitCostRAM.OutputSizeCertificate outputSize function

/-- Choice-uniform output-size certificate for randomized, oracle, or
adversarial executions. -/
abbrev RAMOutputSizeCertificateWithChoice
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (outputSize : (input : Input) → (choice : Choice input) →
      Output input choice → ℕ)
    (function : (input : Input) → (choice : Choice input) →
      Output input choice) :=
  UnitCostRAM.OutputSizeCertificateWithChoice outputSize function

/-- Checked polynomial majorant for every state reached by a counted or
fuelled loop.  Unreachable values of the state type impose no obligation. -/
abbrev RAMIterateStateSizeCertificate
    {Input : Type u} {State : Input → Type v}
    (sizeOf : Input → ℕ)
    (stateSize : (input : Input) → State input → ℕ)
    (iterations : Input → ℕ)
    (step : (input : Input) →
      State input → UnitCostRAM.Cost (State input))
    (initial : (input : Input) → State input) :=
  UnitCostRAM.IterateStateSizeCertificate
    sizeOf stateSize iterations step initial

/-- The output of a mathematical function has polynomial size in an explicit
representation-independent size measure. -/
def FunctionHasPolynomialOutputSize
    {Input : Type u} {Output : Input → Type v}
    (sizeOf : Input → ℕ)
    (outputSize : (input : Input) → Output input → ℕ)
    (function : (input : Input) → Output input) : Prop :=
  UnitCostRAM.HasPolynomialOutputSize sizeOf outputSize function

/-- Representation-aware specialization: the lossless encoded output has
polynomially many unit-cost RAM words. -/
def FunctionHasPolynomialEncodedOutputSize
    {Input : Type u} {Output : Input → Type v}
    (sizeOf : Input → ℕ)
    (encoding : UnitCostRAM.DependentEncoding Output)
    (function : (input : Input) → Output input) : Prop :=
  UnitCostRAM.HasPolynomialEncodedOutputSize sizeOf encoding function

/-- Polynomial output-size bound uniform over all seeds, legal oracles,
tie-breaking rules, or other auxiliary execution choices. -/
def FunctionHasUniformPolynomialOutputSize
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (sizeOf : Input → ℕ)
    (outputSize : (input : Input) → (choice : Choice input) →
      Output input choice → ℕ)
    (function : (input : Input) → (choice : Choice input) →
      Output input choice) : Prop :=
  UnitCostRAM.HasUniformPolynomialOutputSize sizeOf outputSize function

/-- A local running-time bound uniform in the original input and a dependent
intermediate value.  This is the continuation-cost interface used by sound
sequential composition. -/
abbrev RAMPolynomialCostInInputAndValueSize
    {Input : Type u} {Value : Input → Type v}
    (inputSize : Input → ℕ)
    (valueSize : (input : Input) → Value input → ℕ)
    (cost : (input : Input) → Value input → ℕ) :=
  UnitCostRAM.IsPolyBoundInInputAndValueSize inputSize valueSize cost

/-- Choice-uniform local continuation cost in the original input and an
intermediate value. -/
abbrev RAMUniformPolynomialCostInInputAndValueSize
    {Input : Type u} {Choice : Input → Type v}
    {Value : (input : Input) → Choice input → Type w}
    (inputSize : Input → ℕ)
    (valueSize : (input : Input) → (choice : Choice input) →
      Value input choice → ℕ)
    (cost : (input : Input) → (choice : Choice input) →
      Value input choice → ℕ) :=
  UnitCostRAM.IsUniformPolyBoundInInputAndValueSize
    inputSize valueSize cost

/-- A reusable package containing an implementation, its polynomial running
time, and a checked polynomial bound on the size of its output.  The last
component is essential when this implementation is followed by another
algorithm whose cost depends on the representation it receives. -/
structure RAMPolynomialSizeAwareImplementation
    {Input : Type u} {Output : Input → Type v}
    (sizeOf : Input → ℕ)
    (outputSize : (input : Input) → Output input → ℕ)
    (function : (input : Input) → Output input) where
  implementation : RAMCostedImplementation function
  outputSizeCertificate : RAMOutputSizeCertificate outputSize function
  polynomialTime : implementation.IsPolynomial sizeOf
  polynomialOutputSize : outputSizeCertificate.IsPolynomial sizeOf

/-- Symbolic upper-bound language used by the executable checker. -/
abbrev RAMGrowthExpr := UnitCostRAM.StaticComplexity.GrowthExpr

/-- Mathlib-Big-O comparison with an explicit target shape.  Use this when
the distinction between, for example, `n log n` and a coarse quadratic
majorant should remain visible. -/
abbrev AsymptoticCostBound (cost bound : ℕ → ℕ) :=
  UnitCostRAM.StaticComplexity.IsAsymptoticallyBoundedBy cost bound

theorem asymptoticCostBound_of_le
    {cost bound : ℕ → ℕ} (pointwise : ∀ n, cost n ≤ bound n) :
    AsymptoticCostBound cost bound :=
  UnitCostRAM.StaticComplexity.isAsymptoticallyBoundedBy_of_le pointwise

/-- Execute the conservative polynomial-growth decision procedure. -/
def decideRAMGrowthPolynomial (expression : RAMGrowthExpr) : Bool :=
  expression.isPolynomial

/-- Proof-level extraction of a concrete Mathlib polynomial majorant.  The
Boolean decision procedure remains executable; Mathlib's polynomial algebra
is noncomputable data in the current library. -/
noncomputable def ramGrowthPolynomialMajorant?
    (expression : RAMGrowthExpr) : Option (Polynomial ℕ) :=
  expression.polynomialMajorant?

theorem ramGrowthPolynomialMajorant?_sound
    (expression : RAMGrowthExpr) {polynomial : Polynomial ℕ}
    (reported : ramGrowthPolynomialMajorant? expression = some polynomial) :
    ∀ inputSize, expression.eval inputSize ≤ polynomial.eval inputSize :=
  expression.polynomialMajorant?_sound reported

/-- Typed primitive language model used to extract an exact symbolic cost
from the sequence of primitive calls selected during execution. -/
abbrev RAMPrimitiveModel (Instruction : Type u → Type v) :=
  UnitCostRAM.StaticComplexity.PrimitiveModel Instruction

/-- Typed free program whose primitive-level symbolic cost is derived by
traversing the program itself. -/
abbrev RAMPrimitiveProgram (Instruction : Type u → Type v)
    (Result : Type u) :=
  UnitCostRAM.StaticComplexity.PrimitiveProgram Instruction Result

/-- Stateful control-flow syntax with automatically analyzed sequencing,
branches, counted loops, and fuelled while loops. -/
abbrev RAMStructuredProgram
    {Input : Type u} (sizeOf : Input → ℕ) (State : Input → Type v) :=
  UnitCostRAM.StaticComplexity.StructuredProgram sizeOf State

/-- Complete initialization/body/finalization wrapper for a structured
program with a cost expression generated from its executable syntax. -/
abbrev RAMStructuredAlgorithm
    {Input : Type u} (sizeOf : Input → ℕ)
    (State : Input → Type v) (Output : Input → Type w) :=
  UnitCostRAM.StaticComplexity.StructuredAlgorithm sizeOf State Output

/-! ## Two-step strict RAM interface -/

/-- Step 1 for a deterministic function: a fixed-encoding program and its
exact interpreter-generated operation count, without an asymptotic claim. -/
abbrev FixedEncodingRAMImplementation
    {Input : Type u} {Output : Input → Type v}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.DependentEncoding Output)
    (function : (input : Input) → Output input) :=
  UnitCostRAM.FixedEncodingRAMImplementation
    inputEncoding outputEncoding function

/-- Step 1 for randomized/oracle/adversarial execution families. -/
abbrev FixedEnvironmentRAMImplementation
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.ChoiceDependentEncoding Output)
    (ExternalOperation : Type*)
    (environment : (input : Input) →
      Choice input → UnitCostRAM.MachineEnvironment ExternalOperation)
    (function : (input : Input) →
      (choice : Choice input) → Output input choice) :=
  UnitCostRAM.FixedEnvironmentRAMImplementation inputEncoding outputEncoding
    ExternalOperation environment function

/-- Step 1 for a promise search relation. -/
abbrev FixedEncodingRAMSearchImplementation
    {Input : Type u} {Output : Input → Type v}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.DependentEncoding Output)
    (valid : Input → Prop)
    (solution : (input : Input) → Output input → Prop) :=
  UnitCostRAM.FixedEncodingRAMSearchImplementation
    inputEncoding outputEncoding valid solution

/-- Finite instruction-level real-RAM certificate with input/output
representations fixed by the surrounding problem statement and an explicit
polynomial time majorant.  This is the preferred strict interface for new
formalizations. -/
abbrev StrictRAMComputableInPolyTime
    {Input : Type u} {Output : Input → Type v}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.DependentEncoding Output)
    (function : (input : Input) → Output input) :=
  UnitCostRAM.StrictRAMComputableInPolyTime
    inputEncoding outputEncoding function

/-- Preferred choice/oracle strict certificate: external semantics are fixed
outside the program witness. -/
abbrev StrictRAMComputableInPolyTimeWithFixedEnvironment
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.ChoiceDependentEncoding Output)
    (ExternalOperation : Type*)
    (environment : (input : Input) →
      Choice input → UnitCostRAM.MachineEnvironment ExternalOperation)
    (function : (input : Input) →
      (choice : Choice input) → Output input choice) :=
  UnitCostRAM.StrictRAMComputableInPolyTimeWithFixedEnvironment
    inputEncoding outputEncoding ExternalOperation environment function

/-- Fixed-representation instruction-level solver for a dependent search
relation on a promise domain. -/
abbrev StrictRAMSearchableInPolyTime
    {Input : Type u} {Output : Input → Type v}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.DependentEncoding Output)
    (valid : Input → Prop)
    (solution : (input : Input) → Output input → Prop) :=
  UnitCostRAM.StrictRAMSearchableInPolyTime
    inputEncoding outputEncoding valid solution

/-! ## Fixed-representation instruction-enforced RAM predicates

Every public strict predicate in this section receives its encodings before
the program witness.  There is intentionally no predicate of the form
`∃ outputEncoding, ...`: such a witness could install a decoder that computes
the advertised function after the machine halts. -/

/-- Preferred fixed-representation version of strict polynomial time.  The
encodings cannot be selected by the implementation witness. -/
def FunctionRunsInFixedEncodingStrictRAMPolynomialTime
    {Input : Type u} {Output : Input → Type v}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.DependentEncoding Output)
    (function : (input : Input) → Output input) : Prop :=
  Nonempty
    (StrictRAMComputableInPolyTime inputEncoding outputEncoding function)

/-- Preferred fixed-representation, choice-uniform strict polynomial-time
predicate. -/
def FunctionRunsInFixedEncodingStrictRAMPolynomialTimeUniformly
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.ChoiceDependentEncoding Output)
    (ExternalOperation : Type*)
    (environment : (input : Input) →
      Choice input → UnitCostRAM.MachineEnvironment ExternalOperation)
    (function : (input : Input) →
      (choice : Choice input) → Output input choice) : Prop :=
  Nonempty
    (StrictRAMComputableInPolyTimeWithFixedEnvironment
      inputEncoding outputEncoding ExternalOperation environment function)

/-- Fixed-representation strict polynomial time and polynomial oracle-query
usage for the same execution. -/
def FunctionHasFixedEncodingStrictPolynomialTimeAndQueries
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.ChoiceDependentEncoding Output)
    (ExternalOperation : Type*)
    (environment : (input : Input) →
      Choice input → UnitCostRAM.MachineEnvironment ExternalOperation)
    (function : (input : Input) →
      (choice : Choice input) → Output input choice) : Prop :=
  ∃ certificate : StrictRAMComputableInPolyTimeWithFixedEnvironment
      inputEncoding outputEncoding ExternalOperation environment function,
    certificate.HasPolynomialQueries

/-- Fixed-representation strict certificate for all sequential resources
tracked by the machine: time is part of the base certificate, while queries,
samples, random bits, and peak space have explicit polynomial majorants. -/
def FunctionHasFixedEncodingStrictFullyPolynomialResources
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.ChoiceDependentEncoding Output)
    (ExternalOperation : Type*)
    (environment : (input : Input) →
      Choice input → UnitCostRAM.MachineEnvironment ExternalOperation)
    (function : (input : Input) →
      (choice : Choice input) → Output input choice) : Prop :=
  ∃ certificate : StrictRAMComputableInPolyTimeWithFixedEnvironment
      inputEncoding outputEncoding ExternalOperation environment function,
    certificate.HasPolynomialQueries ∧
      certificate.UsesPolynomialSamples ∧
      certificate.UsesPolynomialRandomBits ∧
      certificate.UsesPolynomialSpace

/-- Preferred fixed-representation strict polynomial-time search predicate.
The promise, relation, encodings, finite program, and explicit polynomial are
all visible in the certificate. -/
def SearchRunsInFixedEncodingStrictRAMPolynomialTimeOn
    {Input : Type u} {Output : Input → Type v}
    (inputEncoding : UnitCostRAM.Encoding Input)
    (outputEncoding : UnitCostRAM.DependentEncoding Output)
    (valid : Input → Prop)
    (solution : (input : Input) → Output input → Prop) : Prop :=
  Nonempty
    (StrictRAMSearchableInPolyTime
      inputEncoding outputEncoding valid solution)

/-! ## Uniform indexed families -/

/-- Input to a genuinely uniform indexed algorithm family.  The index is
part of the machine input rather than selecting a different program outside
the execution. -/
abbrev IndexedInput (Index : Type u) (Input : Index → Type v) :=
  Σ index, Input index

/-- A fixed-representation family computed by one program for every index.
This is stronger than `∀ index, ∃ program`, even when the latter programs
share polynomial coefficients: the latter is a nonuniform family with
unbounded program advice. -/
structure FixedEncodingFunctionFamily where
  Index : Type u
  Input : Index → Type v
  Output : (index : Index) → Input index → Type w
  inputEncoding : UnitCostRAM.Encoding (IndexedInput Index Input)
  outputEncoding : UnitCostRAM.DependentEncoding
    (fun packed : IndexedInput Index Input => Output packed.1 packed.2)
  function : (index : Index) → (input : Input index) → Output index input

namespace FixedEncodingFunctionFamily

def packedFunction (family : FixedEncodingFunctionFamily) :
    (packed : IndexedInput family.Index family.Input) →
      family.Output packed.1 packed.2 :=
  fun packed => family.function packed.1 packed.2

/-- One finite strict-RAM program and one explicit polynomial compute the
whole indexed family. -/
def RunsInUniformPolynomialTime
    (family : FixedEncodingFunctionFamily) : Prop :=
  Nonempty
    (StrictRAMComputableInPolyTime
      family.inputEncoding family.outputEncoding family.packedFunction)

end FixedEncodingFunctionFamily

/-! ## Polynomial resource bounds -/

/-- One *specified* polynomial bound on a concrete natural-valued resource.
Unlike `PolynomialCostBound`, this predicate does not existentially choose its
coefficient and exponent.  It is the building block for algorithm-family
statements in which the same constants must be selected before the dimensions
and the corresponding family member:

`∃ c k, ∀ n m, ∃ Aₙₘ, ResourceBound c k ... Aₙₘ`.

This quantifier order is essential.  Writing `∀ n m, ∃ Aₙₘ, ∃ c k, ...`
allows a different hidden polynomial for every fixed input dimension. -/
def ResourceBound
    {Input : Type u} (coefficient exponent : ℕ)
    (sizeOf : Input → ℕ) (cost : Input → ℕ) : Prop :=
  ∀ input,
    cost input ≤ coefficient * (sizeOf input + 1) ^ exponent

/-- Multivariate-size form of `ResourceBound`.  The size parameters are
aggregated by addition, so one fixed pair of constants bounds one polynomial in
all advertised parameters. -/
def ResourceBoundInSizes
    {Input : Type u} (coefficient exponent : ℕ)
    (sizes : Input → List ℕ) (cost : Input → ℕ) : Prop :=
  ResourceBound coefficient exponent
    (fun input => UnitCostRAM.aggregateSize (sizes input)) cost

/-- One specified worst-case polynomial bound, uniform over every seed, legal
oracle, tie-breaking rule, transcript, or other execution choice. -/
def UniformResourceBound
    {Input : Type u} {Choice : Input → Type v}
    (coefficient exponent : ℕ) (sizeOf : Input → ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  ∀ input choice,
    cost input choice ≤ coefficient * (sizeOf input + 1) ^ exponent

/-- Multivariate-size version of `UniformResourceBound`. -/
def UniformResourceBoundInSizes
    {Input : Type u} {Choice : Input → Type v}
    (coefficient exponent : ℕ) (sizes : Input → List ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  ∀ input choice,
    cost input choice ≤
      coefficient *
        (UnitCostRAM.aggregateSize (sizes input) + 1) ^ exponent

/-- Promise-restricted uniform bound with fixed coefficient and exponent. -/
def UniformResourceBoundOn
    {Input : Type u} {Choice : Input → Type v}
    (coefficient exponent : ℕ)
    (valid : (input : Input) → Choice input → Prop)
    (sizeOf : Input → ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  ∀ input choice, valid input choice →
    cost input choice ≤ coefficient * (sizeOf input + 1) ^ exponent

/-- Multivariate-size promise-restricted uniform bound with fixed constants. -/
def UniformResourceBoundInSizesOn
    {Input : Type u} {Choice : Input → Type v}
    (coefficient exponent : ℕ)
    (valid : (input : Input) → Choice input → Prop)
    (sizes : Input → List ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  ∀ input choice, valid input choice →
    cost input choice ≤
      coefficient *
        (UnitCostRAM.aggregateSize (sizes input) + 1) ^ exponent

/-- A dependent function has an implementation whose charged operation count
obeys one *already fixed* multivariate polynomial bound.  This is the
fixed-constant building block for statements of the form
`∃ c k, ∀ n m, ∃ implementationₙₘ, ...`. -/
def FunctionRunsWithinResourceBoundInSizes
    {Input : Type u} {Output : Input → Type v}
    (coefficient exponent : ℕ)
    (sizes : Input → List ℕ)
    (function : (input : Input) → Output input) : Prop :=
  ∃ implementation : RAMCostedImplementation function,
    ResourceBoundInSizes coefficient exponent sizes
      (fun input => (implementation.run input).ops)

/-- Promise-restricted fixed-constant implementation bound. -/
def FunctionRunsWithinResourceBoundInSizesOn
    {Input : Type u} {Output : Input → Type v}
    (coefficient exponent : ℕ)
    (valid : Input → Prop)
    (sizes : Input → List ℕ)
    (function : (input : Input) → Output input) : Prop :=
  ∃ implementation : RAMCostedImplementationOn valid function,
    ∀ input, valid input →
      (implementation.run input).ops ≤
        coefficient *
          (UnitCostRAM.aggregateSize (sizes input) + 1) ^ exponent

/-- A concrete natural-valued resource counter is polynomial in one chosen
input-size measure. -/
def PolynomialCostBound
    {Input : Type u} (sizeOf : Input → ℕ) (cost : Input → ℕ) : Prop :=
  UnitCostRAM.IsPolyBound sizeOf cost

/-- Data-carrying polynomial majorant for an arbitrary natural-valued cost
formula.  Use this when the finite `RAMGrowthExpr` checker does not know a
constructor for a library or user-defined function: the formula is unrestricted,
but its pointwise polynomial majorant must be proved. -/
abbrev PolynomialCostCertificate
    {Input : Type u} (sizeOf : Input → ℕ) (cost : Input → ℕ) :=
  UnitCostRAM.IsPolyBound.PolynomialMajorantCertificate sizeOf cost

/-- The open-ended certificate interface and `PolynomialCostBound` express
exactly the same mathematical property. -/
theorem nonempty_polynomialCostCertificate_iff
    {Input : Type u} (sizeOf : Input → ℕ) (cost : Input → ℕ) :
    Nonempty (PolynomialCostCertificate sizeOf cost) ↔
      PolynomialCostBound sizeOf cost :=
  UnitCostRAM.IsPolyBound.nonempty_polynomialMajorantCertificate_iff

/-- Problem-facing characterization using Mathlib's standard polynomial
datatype rather than the coefficient/exponent normal form. -/
theorem polynomialCostBound_iff_exists_polynomial
    {Input : Type u} (sizeOf : Input → ℕ) (cost : Input → ℕ) :
    PolynomialCostBound sizeOf cost ↔
      ∃ polynomial : Polynomial ℕ, ∀ input,
        cost input ≤ polynomial.eval (sizeOf input) :=
  UnitCostRAM.IsPolyBound.iff_exists_natPolynomial

/-- A concrete resource counter is polynomial in several named size
parameters. -/
def PolynomialCostBoundInSizes
    {Input : Type u} (sizes : Input → List ℕ) (cost : Input → ℕ) : Prop :=
  UnitCostRAM.IsPolyBoundInSizes sizes cost

/-- A genuine multivariate Mathlib-polynomial bound in named size parameters.
Use this form when the distinction between parameters such as numbers of
agents, goods, vertices, and edges should remain visible.  For a fixed finite
parameter type it is equivalent to `PolynomialCostBound` in their sum. -/
def MultivariatePolynomialCostBound
    {Input : Type u} {Parameter : Type v}
    (sizes : Input → Parameter → ℕ) (cost : Input → ℕ) : Prop :=
  UnitCostRAM.IsMvPolynomialBound sizes cost

/-- Data-carrying genuine multivariate majorant for an arbitrary cost
formula. -/
abbrev MultivariatePolynomialCostCertificate
    {Input : Type u} {Parameter : Type v}
    (sizes : Input → Parameter → ℕ) (cost : Input → ℕ) :=
  UnitCostRAM.MvPolynomialMajorantCertificate sizes cost

theorem nonempty_multivariatePolynomialCostCertificate_iff
    {Input : Type u} {Parameter : Type v}
    (sizes : Input → Parameter → ℕ) (cost : Input → ℕ) :
    Nonempty (MultivariatePolynomialCostCertificate sizes cost) ↔
      MultivariatePolynomialCostBound sizes cost :=
  UnitCostRAM.nonempty_mvPolynomialMajorantCertificate_iff

/-- Promise-problem form of `PolynomialCostBound`. -/
def PolynomialCostBoundOn
    {Input : Type u} (valid : Input → Prop)
    (sizeOf : Input → ℕ) (cost : Input → ℕ) : Prop :=
  UnitCostRAM.IsPolyBoundOn valid sizeOf cost

/-- Multivariate-size promise-problem resource bound. -/
def PolynomialCostBoundInSizesOn
    {Input : Type u} (valid : Input → Prop)
    (sizes : Input → List ℕ) (cost : Input → ℕ) : Prop :=
  UnitCostRAM.IsPolyBoundInSizesOn valid sizes cost

/-- Promise-problem form of `MultivariatePolynomialCostBound`. -/
def MultivariatePolynomialCostBoundOn
    {Input : Type u} {Parameter : Type v}
    (valid : Input → Prop) (sizes : Input → Parameter → ℕ)
    (cost : Input → ℕ) : Prop :=
  UnitCostRAM.IsMvPolynomialBoundOn valid sizes cost

/-- A resource counter is polynomial uniformly over a seed, oracle,
tie-breaking rule, transcript, or execution path. -/
def UniformPolynomialCostBound
    {Input : Type u} {Choice : Input → Type v}
    (sizeOf : Input → ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  UnitCostRAM.IsUniformPolyBound sizeOf cost

/-- Multivariate-size version of `UniformPolynomialCostBound`. -/
def UniformPolynomialCostBoundInSizes
    {Input : Type u} {Choice : Input → Type v}
    (sizes : Input → List ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  UnitCostRAM.IsUniformPolyBoundInSizes sizes cost

/-- One genuine multivariate polynomial uniformly bounds all seeds, legal
oracles, tie-breaking rules, or execution paths. -/
def UniformMultivariatePolynomialCostBound
    {Input : Type u} {Parameter : Type v} {Choice : Input → Type w}
    (sizes : Input → Parameter → ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  UnitCostRAM.IsUniformMvPolynomialBound sizes cost

/-- Uniform polynomial bound restricted to legal seeds, oracles,
tie-breaking rules, transcripts, or other execution choices. -/
def UniformPolynomialCostBoundOn
    {Input : Type u} {Choice : Input → Type v}
    (valid : (input : Input) → Choice input → Prop)
    (sizeOf : Input → ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  UnitCostRAM.IsUniformPolyBoundOn valid sizeOf cost

/-- Multivariate-size version of `UniformPolynomialCostBoundOn`. -/
def UniformPolynomialCostBoundInSizesOn
    {Input : Type u} {Choice : Input → Type v}
    (valid : (input : Input) → Choice input → Prop)
    (sizes : Input → List ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  UnitCostRAM.IsUniformPolyBoundInSizesOn valid sizes cost

/-- Promise-restricted uniform genuine multivariate bound. -/
def UniformMultivariatePolynomialCostBoundOn
    {Input : Type u} {Parameter : Type v} {Choice : Input → Type w}
    (valid : (input : Input) → Choice input → Prop)
    (sizes : Input → Parameter → ℕ)
    (cost : (input : Input) → Choice input → ℕ) : Prop :=
  UnitCostRAM.IsUniformMvPolynomialBoundOn valid sizes cost

/-- The named-parameter and aggregate-size definitions agree for every fixed
finite parameter family. -/
theorem multivariatePolynomialCostBound_iff_aggregate
    {Input : Type u} {Parameter : Type v} [Fintype Parameter]
    (sizes : Input → Parameter → ℕ) (cost : Input → ℕ) :
    MultivariatePolynomialCostBound sizes cost ↔
      PolynomialCostBound
        (fun input ↦ ∑ parameter, sizes input parameter) cost :=
  UnitCostRAM.isMvPolynomialBound_iff_aggregate sizes cost

/-- A nonnegative real-valued expected resource usage is polynomially bounded.
This is the appropriate interface when the source explicitly asks for
expected, rather than worst-case, polynomial time or query complexity. -/
def PolynomialExpectedCostBound
    {Input : Type u} (sizeOf : Input → ℕ)
    (expectedCost : Input → ℝ) : Prop :=
  (∀ input, 0 ≤ expectedCost input) ∧
    ∃ coefficient exponent : ℕ,
      ∀ input,
        expectedCost input ≤
          (coefficient * (sizeOf input + 1) ^ exponent : ℕ)

/-- Data-carrying majorant for an arbitrary nonnegative real-valued resource
formula, such as an exact expectation or a formula involving logarithms,
roots, integrals, or other analytic operations.  The framework does not try
to recognize the syntax of `cost`; the checked pointwise inequality is the
sound extension mechanism. -/
structure PolynomialExpectedCostCertificate
    {Input : Type u} (sizeOf : Input → ℕ) (cost : Input → ℝ) where
  polynomial : Polynomial ℕ
  nonnegative : ∀ input, 0 ≤ cost input
  bound : ∀ input,
    cost input ≤ ((polynomial.eval (sizeOf input) : ℕ) : ℝ)

namespace PolynomialExpectedCostCertificate

/-- Every nonnegative uniformly bounded real formula has a constant
polynomial certificate.  This covers, for example, absolute sine/cosine
factors once their standard Mathlib bound has been supplied. -/
noncomputable def ofBounded
    {Input : Type u} {sizeOf : Input → ℕ} {cost : Input → ℝ}
    (upper : ℕ) (nonnegative : ∀ input, 0 ≤ cost input)
    (bound : ∀ input, cost input ≤ (upper : ℝ)) :
    PolynomialExpectedCostCertificate sizeOf cost :=
  ⟨Polynomial.C upper, nonnegative, fun input ↦ by
    simpa using bound input⟩

/-- Certify a real-valued formula by sandwiching it below a certified
natural-valued counter.  This is often the shortest route for floors,
ceilings, logarithms, square roots, and bounded analytic factors. -/
noncomputable def ofNatUpperBound
    {Input : Type u} {sizeOf : Input → ℕ}
    {cost : Input → ℝ} {upper : Input → ℕ}
    (upperCertificate : PolynomialCostCertificate sizeOf upper)
    (nonnegative : ∀ input, 0 ≤ cost input)
    (bound : ∀ input, cost input ≤ (upper input : ℝ)) :
    PolynomialExpectedCostCertificate sizeOf cost :=
  ⟨upperCertificate.polynomial, nonnegative, fun input ↦
    (bound input).trans (by exact_mod_cast upperCertificate.bound input)⟩

/-- Replace a certified real formula by any nonnegative pointwise smaller
formula. -/
def ofLE
    {Input : Type u} {sizeOf : Input → ℕ} {left right : Input → ℝ}
    (rightCertificate : PolynomialExpectedCostCertificate sizeOf right)
    (nonnegative : ∀ input, 0 ≤ left input)
    (bound : ∀ input, left input ≤ right input) :
    PolynomialExpectedCostCertificate sizeOf left :=
  ⟨rightCertificate.polynomial, nonnegative, fun input ↦
    (bound input).trans (rightCertificate.bound input)⟩

/-- Real polynomial-majorant certificates compose under addition. -/
noncomputable def add
    {Input : Type u} {sizeOf : Input → ℕ} {left right : Input → ℝ}
    (leftCertificate : PolynomialExpectedCostCertificate sizeOf left)
    (rightCertificate : PolynomialExpectedCostCertificate sizeOf right) :
    PolynomialExpectedCostCertificate sizeOf
      (fun input ↦ left input + right input) :=
  ⟨leftCertificate.polynomial + rightCertificate.polynomial,
    fun input ↦ add_nonneg (leftCertificate.nonnegative input)
      (rightCertificate.nonnegative input),
    fun input ↦ by
      simpa only [Polynomial.eval_add, Nat.cast_add] using
        add_le_add (leftCertificate.bound input)
          (rightCertificate.bound input)⟩

/-- Real polynomial-majorant certificates compose under multiplication of
nonnegative formulae. -/
noncomputable def mul
    {Input : Type u} {sizeOf : Input → ℕ} {left right : Input → ℝ}
    (leftCertificate : PolynomialExpectedCostCertificate sizeOf left)
    (rightCertificate : PolynomialExpectedCostCertificate sizeOf right) :
    PolynomialExpectedCostCertificate sizeOf
      (fun input ↦ left input * right input) :=
  ⟨leftCertificate.polynomial * rightCertificate.polynomial,
    fun input ↦ mul_nonneg (leftCertificate.nonnegative input)
      (rightCertificate.nonnegative input),
    fun input ↦ by
      rw [Polynomial.eval_mul, Nat.cast_mul]
      exact mul_le_mul (leftCertificate.bound input)
        (rightCertificate.bound input)
        (rightCertificate.nonnegative input)
        (by positivity)⟩

/-- Real polynomial-majorant certificates compose under a fixed natural
power. -/
noncomputable def pow
    {Input : Type u} {sizeOf : Input → ℕ} {cost : Input → ℝ}
    (certificate : PolynomialExpectedCostCertificate sizeOf cost)
    (exponent : ℕ) :
    PolynomialExpectedCostCertificate sizeOf
      (fun input ↦ cost input ^ exponent) :=
  ⟨certificate.polynomial ^ exponent,
    fun input ↦ pow_nonneg (certificate.nonnegative input) exponent,
    fun input ↦ by
      rw [Polynomial.eval_pow, Nat.cast_pow]
      exact pow_le_pow_left₀ (certificate.nonnegative input)
        (certificate.bound input) exponent⟩

end PolynomialExpectedCostCertificate

/-- The real-valued certificate is equivalent to the existing expected-cost
predicate.  Hence an explicit formula need not belong to the symbolic AST;
it only needs a proved polynomial majorant. -/
theorem nonempty_polynomialExpectedCostCertificate_iff
    {Input : Type u} (sizeOf : Input → ℕ) (cost : Input → ℝ) :
    Nonempty (PolynomialExpectedCostCertificate sizeOf cost) ↔
      PolynomialExpectedCostBound sizeOf cost := by
  constructor
  · rintro ⟨certificate⟩
    refine ⟨certificate.nonnegative, ?_⟩
    obtain ⟨coefficient, exponent, polynomialBound⟩ :=
      UnitCostRAM.IsPolyBound.natPolynomialEval_comp
        (sizeOf := sizeOf) certificate.polynomial
    refine ⟨coefficient, exponent, fun input ↦
      (certificate.bound input).trans ?_⟩
    exact_mod_cast polynomialBound input
  · rintro ⟨nonnegative, coefficient, exponent, bound⟩
    let polynomial : Polynomial ℕ :=
      Polynomial.C coefficient * (Polynomial.X + 1) ^ exponent
    refine ⟨⟨polynomial, nonnegative, fun input ↦ ?_⟩⟩
    simpa [polynomial, Polynomial.eval_mul, Polynomial.eval_add,
      Polynomial.eval_pow] using bound input

/-- Standard Mathlib-Big-O endpoint for a nonnegative real-valued cost on
natural input sizes. -/
def IsRealAsymptoticallyPolynomial (cost : ℕ → ℝ) : Prop :=
  ∃ exponent : ℕ,
    cost =O[atTop] (fun n => ((n + 1 : ℕ) : ℝ) ^ exponent)

/-- A global pointwise certificate implies the standard asymptotic
formulation. -/
theorem PolynomialExpectedCostCertificate.isRealAsymptoticallyPolynomial
    {cost : ℕ → ℝ}
    (certificate : PolynomialExpectedCostCertificate id cost) :
    IsRealAsymptoticallyPolynomial cost := by
  have semantic :
      PolynomialExpectedCostBound id cost :=
    nonempty_polynomialExpectedCostCertificate_iff id cost |>.mp
      ⟨certificate⟩
  obtain ⟨nonnegative, coefficient, exponent, bound⟩ := semantic
  refine ⟨exponent, isBigO_iff.mpr ⟨(coefficient : ℝ), ?_⟩⟩
  filter_upwards [] with n
  simp only [Real.norm_eq_abs, abs_pow]
  rw [abs_of_nonneg (nonnegative n), abs_of_nonneg (by positivity)]
  simpa only [Nat.cast_mul, Nat.cast_pow, Nat.cast_add, Nat.cast_one] using
    bound n

/-- On natural input sizes, the global expected-cost predicate is exactly a
nonnegativity proof together with Mathlib's standard asymptotic polynomial
condition.  Thus the pointwise certificate interface does not lose any
nonnegative function that can already be proved polynomial by Mathlib's
`IsBigO` API; the finitely many values before the asymptotic threshold are
absorbed into the natural coefficient. -/
theorem polynomialExpectedCostBound_iff_isRealAsymptoticallyPolynomial
    (cost : ℕ → ℝ) :
    PolynomialExpectedCostBound id cost ↔
      (∀ n, 0 ≤ cost n) ∧ IsRealAsymptoticallyPolynomial cost := by
  constructor
  · intro bound
    obtain ⟨nonnegative, coefficient, exponent, pointwise⟩ := bound
    refine ⟨nonnegative, exponent, isBigO_iff.mpr ⟨(coefficient : ℝ), ?_⟩⟩
    filter_upwards [] with n
    simp only [Real.norm_eq_abs, abs_pow]
    rw [abs_of_nonneg (nonnegative n), abs_of_nonneg (by positivity)]
    simpa only [Nat.cast_mul, Nat.cast_pow, Nat.cast_add, Nat.cast_one] using
      pointwise n
  · rintro ⟨nonnegative, exponent, asymptotic⟩
    obtain ⟨constant, constantPositive, globalBound⟩ :=
      bound_of_isBigO_nat_atTop asymptotic
    obtain ⟨coefficient, coefficientBound⟩ := exists_nat_ge constant
    refine ⟨nonnegative, coefficient, exponent, fun n ↦ ?_⟩
    have comparison := globalBound (x := n) (by positivity :
      (((n + 1 : ℕ) : ℝ) ^ exponent) ≠ 0)
    rw [Real.norm_eq_abs, Real.norm_eq_abs,
      abs_of_nonneg (nonnegative n), abs_of_nonneg (by positivity)] at comparison
    exact comparison.trans <| calc
      constant * (((n + 1 : ℕ) : ℝ) ^ exponent) ≤
          (coefficient : ℝ) * (((n + 1 : ℕ) : ℝ) ^ exponent) :=
        mul_le_mul_of_nonneg_right coefficientBound (by positivity)
      _ = ((coefficient * (n + 1) ^ exponent : ℕ) : ℝ) := by
        norm_num

/-- Multivariate-size version of `PolynomialExpectedCostBound`. -/
def PolynomialExpectedCostBoundInSizes
    {Input : Type u} (sizes : Input → List ℕ)
    (expectedCost : Input → ℝ) : Prop :=
  PolynomialExpectedCostBound
    (fun input => UnitCostRAM.aggregateSize (sizes input)) expectedCost

/-- Expected resource usage bounded by a genuine multivariate polynomial in
named size parameters. -/
def MultivariatePolynomialExpectedCostBound
    {Input : Type u} {Parameter : Type v}
    (sizes : Input → Parameter → ℕ)
    (expectedCost : Input → ℝ) : Prop :=
  (∀ input, 0 ≤ expectedCost input) ∧
    ∃ polynomial : MvPolynomial Parameter ℕ, ∀ input,
      expectedCost input ≤ (polynomial.eval (sizes input) : ℝ)

/-- Data-carrying expected-cost majorant in several named parameters. -/
structure MultivariatePolynomialExpectedCostCertificate
    {Input : Type u} {Parameter : Type v}
    (sizes : Input → Parameter → ℕ) (cost : Input → ℝ) where
  polynomial : MvPolynomial Parameter ℕ
  nonnegative : ∀ input, 0 ≤ cost input
  bound : ∀ input,
    cost input ≤ ((polynomial.eval (sizes input) : ℕ) : ℝ)

theorem nonempty_multivariatePolynomialExpectedCostCertificate_iff
    {Input : Type u} {Parameter : Type v}
    (sizes : Input → Parameter → ℕ) (cost : Input → ℝ) :
    Nonempty (MultivariatePolynomialExpectedCostCertificate sizes cost) ↔
      MultivariatePolynomialExpectedCostBound sizes cost := by
  constructor
  · rintro ⟨certificate⟩
    exact ⟨certificate.nonnegative, certificate.polynomial, certificate.bound⟩
  · rintro ⟨nonnegative, polynomial, bound⟩
    exact ⟨⟨polynomial, nonnegative, bound⟩⟩

/-- Expected polynomial resource usage restricted to inputs satisfying a
promise.  Both nonnegativity and the polynomial bound are required only on
valid inputs. -/
def PolynomialExpectedCostBoundOn
    {Input : Type u} (valid : Input → Prop) (sizeOf : Input → ℕ)
    (expectedCost : Input → ℝ) : Prop :=
  (∀ input, valid input → 0 ≤ expectedCost input) ∧
    ∃ coefficient exponent : ℕ,
      ∀ input, valid input →
        expectedCost input ≤
          (coefficient * (sizeOf input + 1) ^ exponent : ℕ)

/-- Promise-restricted expected multivariate polynomial bound. -/
def MultivariatePolynomialExpectedCostBoundOn
    {Input : Type u} {Parameter : Type v}
    (valid : Input → Prop) (sizes : Input → Parameter → ℕ)
    (expectedCost : Input → ℝ) : Prop :=
  (∀ input, valid input → 0 ≤ expectedCost input) ∧
    ∃ polynomial : MvPolynomial Parameter ℕ, ∀ input,
      valid input →
        expectedCost input ≤ (polynomial.eval (sizes input) : ℝ)

/-- Multivariate-size version of `PolynomialExpectedCostBoundOn`. -/
def PolynomialExpectedCostBoundInSizesOn
    {Input : Type u} (valid : Input → Prop)
    (sizes : Input → List ℕ) (expectedCost : Input → ℝ) : Prop :=
  PolynomialExpectedCostBoundOn valid
    (fun input => UnitCostRAM.aggregateSize (sizes input)) expectedCost

/-! ## Finite randomized executions -/

/-- Expected natural-valued resource usage under a finite seed lottery. -/
noncomputable def expectedNatCost
    {Seed : Type u} [Fintype Seed]
    (distribution : Lottery ℝ Seed) (cost : Seed → ℕ) : ℝ :=
  Lottery.expectedValue distribution fun seed => (cost seed : ℝ)

/-- Polynomial expected resource usage, linked to an actual seed distribution
and an actual per-seed counter. -/
noncomputable def HasPolynomialExpectedCost
    {Input : Type u} {Seed : Type v} [Fintype Seed]
    (distribution : Input → Lottery ℝ Seed) (sizeOf : Input → ℕ)
    (cost : Input → Seed → ℕ) : Prop :=
  PolynomialExpectedCostBound sizeOf fun input =>
    expectedNatCost (distribution input) (cost input)

/-- Multivariate-size version of `HasPolynomialExpectedCost`. -/
noncomputable def HasPolynomialExpectedCostInSizes
    {Input : Type u} {Seed : Type v} [Fintype Seed]
    (distribution : Input → Lottery ℝ Seed) (sizes : Input → List ℕ)
    (cost : Input → Seed → ℕ) : Prop :=
  HasPolynomialExpectedCost distribution
    (fun input => UnitCostRAM.aggregateSize (sizes input)) cost

/-! ### General probability spaces

The finite-lottery definitions above are convenient for finite random seeds.
The following variants also cover continuous seeds and exact samples from
real-valued distributions. -/

/-- Expected natural resource usage under an arbitrary probability measure. -/
noncomputable def measureExpectedNatCost
    {Seed : Type u} [MeasurableSpace Seed]
    (distribution : MeasureTheory.Measure Seed) (cost : Seed → ℕ) : ℝ :=
  ∫ seed, (cost seed : ℝ) ∂distribution

/-- Polynomial expected cost for a measurable, integrable counter under a
possibly continuous seed distribution. -/
noncomputable def HasPolynomialMeasuredExpectedCostInSizes
    {Input : Type u} {Seed : Type v} [MeasurableSpace Seed]
    (distribution : Input → MeasureTheory.Measure Seed)
    (sizes : Input → List ℕ) (cost : Input → Seed → ℕ) : Prop :=
  (∀ input, MeasureTheory.IsProbabilityMeasure (distribution input)) ∧
    (∀ input, MeasureTheory.Integrable
      (fun seed => (cost input seed : ℝ)) (distribution input)) ∧
    PolynomialExpectedCostBoundInSizes sizes fun input =>
      measureExpectedNatCost (distribution input) (cost input)

/-- Bounded-error correctness under an arbitrary probability measure.  The
measurability premise prevents a nonmeasurable success event from receiving
Lean's default measure behavior. -/
def IsMeasureBoundedErrorSearchSolver
    {Input : Type u} {Seed : Type v} [MeasurableSpace Seed]
    {Output : Input → Type w}
    (solution : (input : Input) → Output input → Prop)
    (distribution : Input → MeasureTheory.Measure Seed)
    (run : (input : Input) → Seed → Output input)
    (successThreshold : ℝ) : Prop :=
  0 ≤ successThreshold ∧ successThreshold ≤ 1 ∧
    (∀ input, MeasureTheory.IsProbabilityMeasure (distribution input)) ∧
    (∀ input, MeasurableSet {seed | solution input (run input seed)}) ∧
    ∀ input,
      successThreshold ≤
        (distribution input {seed | solution input (run input seed)}).toReal

/-- Probability of an event under a finite lottery. -/
noncomputable def eventProbability
    {Seed : Type u} [Fintype Seed]
    (distribution : Lottery ℝ Seed) (event : Seed → Prop) : ℝ := by
  classical
  exact Lottery.expectedValue distribution fun seed =>
    if event seed then 1 else 0

/-- Bounded-error correctness of a randomized dependent search solver. -/
noncomputable def IsBoundedErrorSearchSolver
    {Input : Type u} {Seed : Type v} [Fintype Seed]
    {Output : Input → Type w}
    (solution : (input : Input) → Output input → Prop)
    (distribution : Input → Lottery ℝ Seed)
    (run : (input : Input) → Seed → Output input)
    (successThreshold : ℝ) : Prop :=
  0 ≤ successThreshold ∧ successThreshold ≤ 1 ∧
    ∀ input,
      successThreshold ≤
        eventProbability (distribution input) fun seed =>
          solution input (run input seed)

/-- A randomized search implementation with actual costed per-seed runs.
Correctness and expected complexity can now be stated about the same program,
rather than about unrelated numerical hooks. -/
structure RandomizedCostedSearchImplementation
    {Input : Type u} (Seed : Type v) [Fintype Seed]
    {Output : Input → Type w}
    (solution : (input : Input) → Output input → Prop) where
  seedDistribution : Input → Lottery ℝ Seed
  run : (input : Input) → Seed → RAMCost (Output input)

/-- Probability that a costed randomized search implementation returns a
valid solution. -/
noncomputable def RandomizedCostedSearchImplementation.IsBoundedErrorCorrect
    {Input : Type u} {Seed : Type v} [Fintype Seed]
    {Output : Input → Type w}
    {solution : (input : Input) → Output input → Prop}
    (implementation : RandomizedCostedSearchImplementation Seed solution)
    (successThreshold : ℝ) : Prop :=
  IsBoundedErrorSearchSolver solution implementation.seedDistribution
    (fun input seed => (implementation.run input seed).value)
    successThreshold

/-- Expected polynomial running time of the concrete randomized program. -/
noncomputable def RandomizedCostedSearchImplementation.IsExpectedPolynomial
    {Input : Type u} {Seed : Type v} [Fintype Seed]
    {Output : Input → Type w}
    {solution : (input : Input) → Output input → Prop}
    (implementation : RandomizedCostedSearchImplementation Seed solution)
    (sizes : Input → List ℕ) : Prop :=
  HasPolynomialExpectedCostInSizes implementation.seedDistribution sizes
    (fun input seed => (implementation.run input seed).ops)

/-! ## Shared `CostM` integration -/

/-- Measure the cost component of any existing `CostM` algorithm by a
natural-valued projection and ask whether the result is polynomial.  This
supports time (`C = ℕ`), a coordinate of a product resource, the cardinality
of a visited-state set, peak memory, or any future cost monoid without
duplicating the algorithm. -/
def CostMHasPolynomialMeasuredCost
    {C : Type u} {Input : Type v} {Output : Input → Type w}
    (measure : C → ℕ) (sizeOf : Input → ℕ)
    (run : (input : Input) → CostM C (Output input)) : Prop :=
  PolynomialCostBound sizeOf (fun input => measure (run input).cost)

/-- Multivariate-size version of `CostMHasPolynomialMeasuredCost`. -/
def CostMHasPolynomialMeasuredCostInSizes
    {C : Type u} {Input : Type v} {Output : Input → Type w}
    (measure : C → ℕ) (sizes : Input → List ℕ)
    (run : (input : Input) → CostM C (Output input)) : Prop :=
  PolynomialCostBoundInSizes sizes
    (fun input => measure (run input).cost)

/-- Worst-case polynomial measured `CostM` cost uniformly over an auxiliary
seed, oracle, path, or tie-breaking rule. -/
def CostMHasUniformPolynomialMeasuredCostInSizes
    {C : Type u} {Input : Type v} {Choice : Input → Type w}
    {Output : (input : Input) → Choice input → Type*}
    (measure : C → ℕ) (sizes : Input → List ℕ)
    (run : (input : Input) →
      (choice : Choice input) → CostM C (Output input choice)) : Prop :=
  (∀ input, Nonempty (Choice input)) ∧
    UniformPolynomialCostBoundInSizes sizes
      (fun input choice => measure (run input choice).cost)

/-- A family of `CostM` algorithms has one polynomial measured-cost bound
uniform over every admissible family member, input, and auxiliary execution
choice.  The cost type itself may depend on the algorithm; `measure` selects
the natural-valued resource to be bounded. -/
def CostMFamilyHasUniformPolynomialMeasuredCostInSizes
    {Algorithm : Type u} {C : Algorithm → Type v}
    {Input : Algorithm → Type w}
    {Choice : (algorithm : Algorithm) → Input algorithm → Type*}
    {Output : (algorithm : Algorithm) →
      (input : Input algorithm) → Choice algorithm input → Type*}
    (admissible : Algorithm → Prop)
    (measure : (algorithm : Algorithm) → C algorithm → ℕ)
    (sizes : (algorithm : Algorithm) → Input algorithm → List ℕ)
    (run : (algorithm : Algorithm) →
      (input : Input algorithm) →
        (choice : Choice algorithm input) →
          CostM (C algorithm) (Output algorithm input choice)) : Prop :=
  (∀ algorithm, admissible algorithm →
      ∀ input, Nonempty (Choice algorithm input)) ∧
    ∃ coefficient exponent : ℕ,
      ∀ algorithm, admissible algorithm →
        ∀ input choice,
          measure algorithm (run algorithm input choice).cost ≤
            coefficient *
              (UnitCostRAM.aggregateSize (sizes algorithm input) + 1) ^ exponent

/-! ## Fully profiled real-RAM implementations -/

/-- A function implementation whose time, oracle, randomness, communication,
and peak-space counters are produced by the same run. -/
structure ProfiledRAMImplementation
    {Input : Type u} {Output : Input → Type v}
    (function : (input : Input) → Output input) where
  run : (input : Input) → UnitCostRAM.ProfiledCost (Output input)
  correct : ∀ input, (run input).ret = function input

namespace ProfiledRAMImplementation

/-- One fixed multivariate polynomial bound for the step counter of this
profiled implementation. -/
def HasTimeBound
    {Input : Type u} {Output : Input → Type v}
    {function : (input : Input) → Output input}
    (implementation : ProfiledRAMImplementation function)
    (coefficient exponent : ℕ)
    (sizes : Input → List ℕ) : Prop :=
  ResourceBoundInSizes coefficient exponent sizes fun input =>
    UnitCostRAM.ProfiledCost.steps (implementation.run input)

/-- One fixed multivariate polynomial bound for the oracle-query counter of
this profiled implementation. -/
def HasQueryBound
    {Input : Type u} {Output : Input → Type v}
    {function : (input : Input) → Output input}
    (implementation : ProfiledRAMImplementation function)
    (coefficient exponent : ℕ)
    (sizes : Input → List ℕ) : Prop :=
  ResourceBoundInSizes coefficient exponent sizes fun input =>
    UnitCostRAM.ProfiledCost.oracleQueries (implementation.run input)

def HasPolynomialTime
    {Input : Type u} {Output : Input → Type v}
    {function : (input : Input) → Output input}
    (implementation : ProfiledRAMImplementation function)
    (sizes : Input → List ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes fun input =>
    UnitCostRAM.ProfiledCost.steps (implementation.run input)

def HasPolynomialQueries
    {Input : Type u} {Output : Input → Type v}
    {function : (input : Input) → Output input}
    (implementation : ProfiledRAMImplementation function)
    (sizes : Input → List ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes fun input =>
    UnitCostRAM.ProfiledCost.oracleQueries (implementation.run input)

def HasPolynomialRandomness
    {Input : Type u} {Output : Input → Type v}
    {function : (input : Input) → Output input}
    (implementation : ProfiledRAMImplementation function)
    (sizes : Input → List ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes fun input =>
    UnitCostRAM.ProfiledCost.randomBits (implementation.run input)

def HasPolynomialSamples
    {Input : Type u} {Output : Input → Type v}
    {function : (input : Input) → Output input}
    (implementation : ProfiledRAMImplementation function)
    (sizes : Input → List ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes fun input =>
    UnitCostRAM.ProfiledCost.distributionSamples (implementation.run input)

def HasPolynomialCommunication
    {Input : Type u} {Output : Input → Type v}
    {function : (input : Input) → Output input}
    (implementation : ProfiledRAMImplementation function)
    (sizes : Input → List ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes fun input =>
    UnitCostRAM.ProfiledCost.communicationUnits (implementation.run input)

def HasPolynomialSpace
    {Input : Type u} {Output : Input → Type v}
    {function : (input : Input) → Output input}
    (implementation : ProfiledRAMImplementation function)
    (sizes : Input → List ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes fun input =>
    UnitCostRAM.ProfiledCost.peakCells (implementation.run input)

/-- All standard resource counters are polynomial for the same concrete run.
Individual applications may require only a selected subset. -/
def HasFullyPolynomialResources
    {Input : Type u} {Output : Input → Type v}
    {function : (input : Input) → Output input}
    (implementation : ProfiledRAMImplementation function)
    (sizes : Input → List ℕ) : Prop :=
  implementation.HasPolynomialTime sizes ∧
    implementation.HasPolynomialQueries sizes ∧
    implementation.HasPolynomialSamples sizes ∧
    implementation.HasPolynomialRandomness sizes ∧
    implementation.HasPolynomialCommunication sizes ∧
    implementation.HasPolynomialSpace sizes

end ProfiledRAMImplementation

/-! ## Uniform families of algorithms -/

/-- A completely generic natural-valued resource accounting model.

`Algorithm` may itself be a dependent package containing the problem domain,
an implementation, and any static parameters.  `Execution` represents the
remaining run-dependent choice: use `Unit` for deterministic execution, a
random seed for worst-case randomized complexity, a subtype of legal oracles
for oracle algorithms, or a complete transcript/path for interactive ones.
The same structure can measure time, work, depth, queries, communication,
space, samples, output delay, or another natural-valued resource. -/
structure PolynomialResourceModel (Algorithm : Type u) where
  Input : Algorithm → Type v
  Execution : (algorithm : Algorithm) → Input algorithm → Type w
  /-- Every advertised input admits at least one execution. -/
  execution_nonempty : ∀ algorithm input, Nonempty (Execution algorithm input)
  sizes : (algorithm : Algorithm) → Input algorithm → List ℕ
  usage : (algorithm : Algorithm) →
    (input : Input algorithm) → Execution algorithm input → ℕ

namespace PolynomialResourceModel

/-- One fixed algorithm has a polynomial worst-case resource bound over all
of its advertised executions.  The hidden constants may depend on this fixed
algorithm. -/
def IsPolynomialFor
    {Algorithm : Type u} (model : PolynomialResourceModel Algorithm)
    (algorithm : Algorithm) : Prop :=
  UniformPolynomialCostBoundInSizes (model.sizes algorithm)
    (model.usage algorithm)

/-- Promise-problem version of `IsPolynomialFor`.  Invalid inputs impose no
resource requirement. -/
def IsPolynomialForOn
    {Algorithm : Type u} (model : PolynomialResourceModel Algorithm)
    (algorithm : Algorithm) (valid : model.Input algorithm → Prop) : Prop :=
  ∃ coefficient exponent : ℕ,
    ∀ input, valid input →
      ∀ execution,
        model.usage algorithm input execution ≤
          coefficient *
            (UnitCostRAM.aggregateSize (model.sizes algorithm input) + 1) ^
              exponent

/-- A class of algorithms has one polynomial bound with constants uniform
over the whole class.  This is the correct predicate for an algorithm family
whose member varies with the problem domain or size. -/
def IsUniformlyPolynomial
    {Algorithm : Type u} (model : PolynomialResourceModel Algorithm)
    (admissible : Algorithm → Prop) : Prop :=
  ∃ coefficient exponent : ℕ,
    ∀ algorithm, admissible algorithm →
      ∀ input execution,
        model.usage algorithm input execution ≤
          coefficient *
            (UnitCostRAM.aggregateSize (model.sizes algorithm input) + 1) ^
              exponent

/-- Promise-problem version of `IsUniformlyPolynomial`.  The constants are
uniform over the algorithm family and every valid input; neither may choose
its own hidden polynomial. -/
def IsUniformlyPolynomialOn
    {Algorithm : Type u} (model : PolynomialResourceModel Algorithm)
    (admissible : Algorithm → Prop)
    (valid : (algorithm : Algorithm) → model.Input algorithm → Prop) : Prop :=
  ∃ coefficient exponent : ℕ,
    ∀ algorithm, admissible algorithm →
      ∀ input, valid algorithm input →
        ∀ execution,
          model.usage algorithm input execution ≤
            coefficient *
              (UnitCostRAM.aggregateSize (model.sizes algorithm input) + 1) ^
                exponent

/-- Uniform polynomial expected resource usage across a family.  The
expectation has already been taken by `expectedUsage`, so no finiteness or
distribution representation is imposed here. -/
def IsUniformlyExpectedPolynomial
    {Algorithm : Type u} (model : PolynomialResourceModel Algorithm)
    (admissible : Algorithm → Prop)
    (expectedUsage : (algorithm : Algorithm) → model.Input algorithm → ℝ) : Prop :=
  (∀ algorithm, admissible algorithm →
      ∀ input, 0 ≤ expectedUsage algorithm input) ∧
    ∃ coefficient exponent : ℕ,
      ∀ algorithm, admissible algorithm →
        ∀ input,
          expectedUsage algorithm input ≤
            (coefficient *
              (UnitCostRAM.aggregateSize (model.sizes algorithm input) + 1) ^
                exponent : ℕ)

/-- Promise-problem version of `IsUniformlyExpectedPolynomial`.  The caller
must separately establish that `expectedUsage` is the expectation of
`model.usage` under the intended execution distribution. -/
def IsUniformlyExpectedPolynomialOn
    {Algorithm : Type u} (model : PolynomialResourceModel Algorithm)
    (admissible : Algorithm → Prop)
    (valid : (algorithm : Algorithm) → model.Input algorithm → Prop)
    (expectedUsage : (algorithm : Algorithm) → model.Input algorithm → ℝ) : Prop :=
  (∀ algorithm, admissible algorithm →
      ∀ input, valid algorithm input →
        0 ≤ expectedUsage algorithm input) ∧
    ∃ coefficient exponent : ℕ,
      ∀ algorithm, admissible algorithm →
        ∀ input, valid algorithm input →
          expectedUsage algorithm input ≤
            (coefficient *
              (UnitCostRAM.aggregateSize (model.sizes algorithm input) + 1) ^
                exponent : ℕ)

end PolynomialResourceModel

/-- A family of concrete RAM implementations has a single polynomial running
time bound uniform over every admissible family member. -/
def RAMImplementationFamilyRunsInPolynomialTimeInSizes
    {Algorithm : Type u} {Input : Algorithm → Type v}
    {Output : (algorithm : Algorithm) → Input algorithm → Type w}
    {function : (algorithm : Algorithm) →
      (input : Input algorithm) → Output algorithm input}
    (admissible : Algorithm → Prop)
    (sizes : (algorithm : Algorithm) → Input algorithm → List ℕ)
    (implementation : (algorithm : Algorithm) →
      RAMCostedImplementation (function algorithm)) : Prop :=
  ∃ coefficient exponent : ℕ,
    ∀ algorithm, admissible algorithm →
      ∀ input,
        ((implementation algorithm).run input).ops ≤
          coefficient *
            (UnitCostRAM.aggregateSize (sizes algorithm input) + 1) ^ exponent

/-- Choice-dependent counterpart of
`RAMImplementationFamilyRunsInPolynomialTimeInSizes`.  One polynomial must
bound every admissible algorithm, input, and seed/oracle/execution choice. -/
def RAMImplementationWithChoiceFamilyRunsInPolynomialTimeInSizes
    {Algorithm : Type u} {Input : Algorithm → Type v}
    {Choice : (algorithm : Algorithm) → Input algorithm → Type w}
    {Output : (algorithm : Algorithm) →
      (input : Input algorithm) → Choice algorithm input → Type*}
    {function : (algorithm : Algorithm) →
      (input : Input algorithm) →
        (choice : Choice algorithm input) →
          Output algorithm input choice}
    (admissible : Algorithm → Prop)
    (sizes : (algorithm : Algorithm) → Input algorithm → List ℕ)
    (implementation : (algorithm : Algorithm) →
      RAMCostedImplementationWithChoice (function algorithm)) : Prop :=
  ∃ coefficient exponent : ℕ,
    ∀ algorithm, admissible algorithm →
      ∀ input choice,
        ((implementation algorithm).run input choice).ops ≤
          coefficient *
            (UnitCostRAM.aggregateSize (sizes algorithm input) + 1) ^ exponent

/-! ## Functions and search problems -/

/-- Legacy predicate asserting a polynomial trusted `CostM` annotation.
It is retained for compatibility and compositional accounting; it is not the
preferred definition of machine-enforced polynomial time. -/
def FunctionRunsInPolynomialTime
    {Input : Type u} {Output : Input → Type v}
    (sizeOf : Input → ℕ) (function : (input : Input) → Output input) : Prop :=
  UnitCostRAM.RunsInPolynomialTime sizeOf function

/-- Multivariate-size version of `FunctionRunsInPolynomialTime`. -/
def FunctionRunsInPolynomialTimeInSizes
    {Input : Type u} {Output : Input → Type v}
    (sizes : Input → List ℕ) (function : (input : Input) → Output input) : Prop :=
  UnitCostRAM.RunsInPolynomialTimeInSizes sizes function

/-- Promise-restricted legacy trusted-instrumentation predicate. -/
def FunctionRunsInPolynomialTimeOn
    {Input : Type u} {Output : Input → Type v}
    (valid : Input → Prop) (sizeOf : Input → ℕ)
    (function : (input : Input) → Output input) : Prop :=
  UnitCostRAM.RunsInPolynomialTimeOn valid sizeOf function

/-- Multivariate-size version of `FunctionRunsInPolynomialTimeOn`. -/
def FunctionRunsInPolynomialTimeInSizesOn
    {Input : Type u} {Output : Input → Type v}
    (valid : Input → Prop) (sizes : Input → List ℕ)
    (function : (input : Input) → Output input) : Prop :=
  UnitCostRAM.RunsInPolynomialTimeInSizesOn valid sizes function

/-- Legacy trusted-instrumentation predicate for a search solver. -/
def SearchRunsInPolynomialTime
    {Input : Type u} {Output : Input → Type v}
    (sizeOf : Input → ℕ)
    (solution : (input : Input) → Output input → Prop) : Prop :=
  UnitCostRAM.SearchRunsInPolynomialTime sizeOf solution

/-- Multivariate-size version of `SearchRunsInPolynomialTime`. -/
def SearchRunsInPolynomialTimeInSizes
    {Input : Type u} {Output : Input → Type v}
    (sizes : Input → List ℕ)
    (solution : (input : Input) → Output input → Prop) : Prop :=
  UnitCostRAM.SearchRunsInPolynomialTimeInSizes sizes solution

/-- Worst-case polynomial time uniformly over an auxiliary seed, oracle, or
adversarial choice. -/
def FunctionRunsInPolynomialTimeUniformly
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (sizeOf : Input → ℕ)
    (function : (input : Input) →
      (choice : Choice input) → Output input choice) : Prop :=
  UnitCostRAM.RunsInPolynomialTimeUniformly sizeOf function

/-- Multivariate-size version of
`FunctionRunsInPolynomialTimeUniformly`. -/
def FunctionRunsInPolynomialTimeInSizesUniformly
    {Input : Type u} {Choice : Input → Type v}
    {Output : (input : Input) → Choice input → Type w}
    (sizes : Input → List ℕ)
    (function : (input : Input) →
      (choice : Choice input) → Output input choice) : Prop :=
  UnitCostRAM.RunsInPolynomialTimeInSizesUniformly sizes function

/-! ## Arbitrary algorithm structures -/

/-- Attach polynomial running time to the behavior projected from any
algorithm structure.  No inheritance or typeclass instance is required of the
algorithm type. -/
def AlgorithmRunsInPolynomialTime
    {Algorithm : Type u} {Input : Algorithm → Type v}
    {Output : (algorithm : Algorithm) → Input algorithm → Type w}
    (algorithm : Algorithm) (sizeOf : Input algorithm → ℕ)
    (run : (algorithm : Algorithm) →
      (input : Input algorithm) → Output algorithm input) : Prop :=
  FunctionRunsInPolynomialTime sizeOf (run algorithm)

/-- Multivariate-size version of `AlgorithmRunsInPolynomialTime`. -/
def AlgorithmRunsInPolynomialTimeInSizes
    {Algorithm : Type u} {Input : Algorithm → Type v}
    {Output : (algorithm : Algorithm) → Input algorithm → Type w}
    (algorithm : Algorithm) (sizes : Input algorithm → List ℕ)
    (run : (algorithm : Algorithm) →
      (input : Input algorithm) → Output algorithm input) : Prop :=
  FunctionRunsInPolynomialTimeInSizes sizes (run algorithm)

/-- Attach an explicit polynomial resource counter to an arbitrary algorithm
structure.  The counter may represent RAM operations, queries, communicated
bits, memory cells, samples, or another natural-valued resource. -/
def AlgorithmHasPolynomialResourceUsage
    {Algorithm : Type u} {Input : Algorithm → Type v}
    (algorithm : Algorithm) (sizeOf : Input algorithm → ℕ)
    (usage : (algorithm : Algorithm) → Input algorithm → ℕ) : Prop :=
  PolynomialCostBound sizeOf (usage algorithm)

/-- Multivariate-size version of
`AlgorithmHasPolynomialResourceUsage`. -/
def AlgorithmHasPolynomialResourceUsageInSizes
    {Algorithm : Type u} {Input : Algorithm → Type v}
    (algorithm : Algorithm) (sizes : Input algorithm → List ℕ)
    (usage : (algorithm : Algorithm) → Input algorithm → ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes (usage algorithm)

/-- Uniform resource bound for an algorithm whose execution also depends on
a seed, oracle, tie-breaking rule, transcript, or path. -/
def AlgorithmHasUniformPolynomialResourceUsage
    {Algorithm : Type u} {Input : Algorithm → Type v}
    {Choice : (algorithm : Algorithm) → Input algorithm → Type w}
    (algorithm : Algorithm) (sizeOf : Input algorithm → ℕ)
    (usage : (algorithm : Algorithm) →
      (input : Input algorithm) → Choice algorithm input → ℕ) : Prop :=
  UniformPolynomialCostBound sizeOf (usage algorithm)

/-- Multivariate-size version of
`AlgorithmHasUniformPolynomialResourceUsage`. -/
def AlgorithmHasUniformPolynomialResourceUsageInSizes
    {Algorithm : Type u} {Input : Algorithm → Type v}
    {Choice : (algorithm : Algorithm) → Input algorithm → Type w}
    (algorithm : Algorithm) (sizes : Input algorithm → List ℕ)
    (usage : (algorithm : Algorithm) →
      (input : Input algorithm) → Choice algorithm input → ℕ) : Prop :=
  UniformPolynomialCostBoundInSizes sizes (usage algorithm)

/-! ## Named resource-counter interfaces -/

/-- A concrete query-count function is polynomially bounded in one size
measure. -/
abbrev PolynomialQueryBound {Input : Type u} :=
  UnitCostRAM.UsesPolynomiallyManyQueries (Input := Input)

/-- A concrete query-count function is polynomial in several named sizes. -/
def PolynomialQueryBoundInSizes
    {Input : Type u} (sizes : Input → List ℕ)
    (queryCount : Input → ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes queryCount

/-- Worst-case polynomial query count uniformly over an auxiliary choice. -/
def UniformPolynomialQueryBound
    {Input : Type u} {Choice : Input → Type v}
    (sizeOf : Input → ℕ)
    (queryCount : (input : Input) → Choice input → ℕ) : Prop :=
  UniformPolynomialCostBound sizeOf queryCount

/-- Multivariate-size version of `UniformPolynomialQueryBound`. -/
def UniformPolynomialQueryBoundInSizes
    {Input : Type u} {Choice : Input → Type v}
    (sizes : Input → List ℕ)
    (queryCount : (input : Input) → Choice input → ℕ) : Prop :=
  UniformPolynomialCostBoundInSizes sizes queryCount

/-- A concrete communicated-bit counter is polynomially bounded in one size
measure. -/
abbrev PolynomialCommunicationBound {Input : Type u} :=
  UnitCostRAM.UsesPolynomialCommunication (Input := Input)

/-- A communicated-bit counter is polynomial in several named sizes. -/
def PolynomialCommunicationBoundInSizes
    {Input : Type u} (sizes : Input → List ℕ)
    (communicatedBits : Input → ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes communicatedBits

/-- Worst-case multivariate polynomial communication uniformly over an
auxiliary choice or transcript. -/
def UniformPolynomialCommunicationBoundInSizes
    {Input : Type u} {Choice : Input → Type v}
    (sizes : Input → List ℕ)
    (communicatedBits : (input : Input) → Choice input → ℕ) : Prop :=
  UniformPolynomialCostBoundInSizes sizes communicatedBits

/-- Polynomially many simultaneously used RAM cells. -/
def PolynomialSpaceBound
    {Input : Type u} (sizeOf : Input → ℕ)
    (cellsUsed : Input → ℕ) : Prop :=
  PolynomialCostBound sizeOf cellsUsed

/-- Multivariate-size polynomial space. -/
def PolynomialSpaceBoundInSizes
    {Input : Type u} (sizes : Input → List ℕ)
    (cellsUsed : Input → ℕ) : Prop :=
  PolynomialCostBoundInSizes sizes cellsUsed

/-- Polynomial space uniformly over a seed, oracle, or execution path. -/
def UniformPolynomialSpaceBoundInSizes
    {Input : Type u} {Choice : Input → Type v}
    (sizes : Input → List ℕ)
    (cellsUsed : (input : Input) → Choice input → ℕ) : Prop :=
  UniformPolynomialCostBoundInSizes sizes cellsUsed

/-! ## Explicit communication protocols -/

/-- One message in a multi-party protocol.  The payload type is deliberately
generic: use `List Bool` for bit complexity and `List UnitCostRAM.Word` for
unit-cost real-RAM word complexity.  Sender and receiver are routing metadata. -/
structure CommunicationMessage (Party : Type u) (Message : Type v) where
  sender : Party
  receiver : Party
  payload : Message

abbrev CommunicationTranscript (Party : Type u) (Message : Type v) :=
  List (CommunicationMessage Party Message)

/-- Total communication according to an explicit size assigned to each
payload. -/
def communicationCost {Party : Type u} {Message : Type v}
    (messageSize : Message → ℕ)
    (transcript : CommunicationTranscript Party Message) : ℕ :=
  (transcript.map fun message => messageSize message.payload).sum

/-- A finite deterministic communication tree with private inputs.  At a send
node, the message may inspect only the sender's private input.  Dependence on
earlier public messages is represented by the already selected path in the
tree.  Thus the model cannot hide a centralized computation that reads the
whole input profile while reporting an empty transcript. -/
inductive CommunicationTree
    (Party : Type u) (PrivateInput : Party → Type v)
    (Message : Type w) (Output : Type*)
  | output (value : Output)
  | send (sender receiver : Party)
      (message : PrivateInput sender → Message)
      (next : Message → CommunicationTree Party PrivateInput Message Output)

/-- Execute a communication tree and retain its complete public transcript. -/
def CommunicationTree.run
    {Party : Type u} {PrivateInput : Party → Type v}
    {Message : Type w} {Output : Type*}
    (profile : (party : Party) → PrivateInput party) :
    CommunicationTree Party PrivateInput Message Output →
      Output × CommunicationTranscript Party Message
  | .output value => (value, [])
  | .send sender receiver message next =>
      let payload := message (profile sender)
      let result := (next payload).run profile
      (result.1, ⟨sender, receiver, payload⟩ :: result.2)

/-- A deterministic distributed protocol computes a function of a profile of
private inputs by one finite communication tree. -/
structure CommunicationProtocol
    (Party : Type u) (PrivateInput : Party → Type v) (Message : Type w)
    {Output : Type*}
    (function : ((party : Party) → PrivateInput party) → Output) where
  tree : CommunicationTree Party PrivateInput Message Output
  correct : ∀ profile, (tree.run profile).1 = function profile

/-- Polynomial communication of one concrete protocol. -/
def CommunicationProtocol.HasPolynomialCommunication
    {Party : Type u} {PrivateInput : Party → Type v} {Message : Type w}
    {Output : Type*}
    {function : ((party : Party) → PrivateInput party) → Output}
    (protocol : CommunicationProtocol Party PrivateInput Message function)
    (messageSize : Message → ℕ)
    (sizes : ((party : Party) → PrivateInput party) → List ℕ) : Prop :=
  PolynomialCommunicationBoundInSizes sizes fun input =>
    communicationCost messageSize (protocol.tree.run input).2

/-- One already fixed multivariate polynomial bound for the actual public
transcript produced by a deterministic protocol. -/
def CommunicationProtocol.HasCommunicationBound
    {Party : Type u} {PrivateInput : Party → Type v} {Message : Type w}
    {Output : Type*}
    {function : ((party : Party) → PrivateInput party) → Output}
    (protocol : CommunicationProtocol Party PrivateInput Message function)
    (coefficient exponent : ℕ)
    (messageSize : Message → ℕ)
    (sizes : ((party : Party) → PrivateInput party) → List ℕ) : Prop :=
  ResourceBoundInSizes coefficient exponent sizes fun input =>
    communicationCost messageSize (protocol.tree.run input).2

/-! ## Potential-method amortized analysis -/

def runOperationSequence
    {State : Type u} {Operation : Type v}
    (next : State → Operation → State) : List Operation → State → State
  | [], state => state
  | operation :: operations, state =>
      runOperationSequence next operations (next state operation)

def operationSequenceCost
    {State : Type u} {Operation : Type v}
    (next : State → Operation → State)
    (actualCost : State → Operation → ℕ) : List Operation → State → ℕ
  | [], _ => 0
  | operation :: operations, state =>
      actualCost state operation +
        operationSequenceCost next actualCost operations
          (next state operation)

/-- Potential-method certificate. The inequality is the subtraction-free form
`actual + Φ(after) ≤ charged + Φ(before)`, convenient over naturals. -/
structure AmortizedCertificate
    (State : Type u) (Operation : Type v)
    (next : State → Operation → State)
    (actualCost : State → Operation → ℕ)
    (chargedCost : Operation → ℕ) where
  potential : State → ℕ
  step_bound : ∀ state operation,
    actualCost state operation + potential (next state operation) ≤
      chargedCost operation + potential state

/-- Telescoping theorem for the potential method. -/
theorem AmortizedCertificate.sequence_bound
    {State : Type u} {Operation : Type v}
    {next : State → Operation → State}
    {actualCost : State → Operation → ℕ}
    {chargedCost : Operation → ℕ}
    (certificate :
      AmortizedCertificate State Operation next actualCost chargedCost)
    (operations : List Operation) (initial : State) :
    operationSequenceCost next actualCost operations initial +
        certificate.potential
          (runOperationSequence next operations initial) ≤
      (operations.map chargedCost).sum + certificate.potential initial := by
  induction operations generalizing initial with
  | nil => simp [operationSequenceCost, runOperationSequence]
  | cons operation operations ih =>
      simp only [operationSequenceCost, runOperationSequence, List.map_cons,
        List.sum_cons]
      have hstep := certificate.step_bound initial operation
      have htail := ih (next initial operation)
      omega

/-- Consequence usually quoted in amortized analysis: total actual cost is at
most total charged cost plus the initial potential. -/
theorem AmortizedCertificate.total_actual_le
    {State : Type u} {Operation : Type v}
    {next : State → Operation → State}
    {actualCost : State → Operation → ℕ}
    {chargedCost : Operation → ℕ}
    (certificate :
      AmortizedCertificate State Operation next actualCost chargedCost)
    (operations : List Operation) (initial : State) :
    operationSequenceCost next actualCost operations initial ≤
      (operations.map chargedCost).sum + certificate.potential initial := by
  exact (Nat.le_add_right _ _).trans
    (certificate.sequence_bound operations initial)

/-! ## Fixed-representation search problems -/

/-- A dependent search problem whose unit-cost RAM representations are part
of the statement rather than chosen by an algorithm witness.  This is the
preferred carrier for complexity-class membership and reductions.

The mathematical `Input` and `Output` types may contain proof fields; only the
fixed lossless encodings determine their computational size. -/
structure FixedEncodingSearchProblem where
  Input : Type u
  Output : Input → Type v
  validInput : Input → Prop
  isSolution : (input : Input) → Output input → Prop
  inputEncoding : UnitCostRAM.Encoding Input
  outputEncoding : UnitCostRAM.DependentEncoding Output

namespace FixedEncodingSearchProblem

def inputSize (problem : FixedEncodingSearchProblem) : problem.Input → ℕ :=
  problem.inputEncoding.size

def outputSize (problem : FixedEncodingSearchProblem) :
    (input : problem.Input) → problem.Output input → ℕ :=
  problem.outputEncoding.size

def IsTotal (problem : FixedEncodingSearchProblem) : Prop :=
  ∀ input, problem.validInput input →
    ∃ output, problem.isSolution input output

def IsPolynomiallyBalanced (problem : FixedEncodingSearchProblem) : Prop :=
  ∃ coefficient exponent : ℕ,
    ∀ input output, problem.validInput input →
      problem.isSolution input output →
        problem.outputSize input output ≤
          coefficient * (problem.inputSize input + 1) ^ exponent

/-- The relation has a finite instruction-level solver with an explicit
polynomial majorant in the fixed input representation. -/
def HasPolynomialTimeSolver (problem : FixedEncodingSearchProblem) : Prop :=
  Nonempty
    (StrictRAMSearchableInPolyTime
      problem.inputEncoding problem.outputEncoding
      problem.validInput problem.isSolution)

end FixedEncodingSearchProblem

/-! ## Legacy search problems and explicit polynomial reductions -/

/-- A representation-aware dependent search problem. Totality and efficient
verification are separate predicates, so ordinary and total search problems
share one reduction interface. -/
structure SearchProblem where
  Input : Type u
  Output : Input → Type v
  validInput : Input → Prop
  isSolution : (input : Input) → Output input → Prop
  inputSize : Input → ℕ
  outputSize : (input : Input) → Output input → ℕ

/-- Forget the fixed encodings while retaining their induced word-size
functions. -/
def FixedEncodingSearchProblem.toSearchProblem
    (problem : FixedEncodingSearchProblem) : SearchProblem :=
  { Input := problem.Input
    Output := problem.Output
    validInput := problem.validInput
    isSolution := problem.isSolution
    inputSize := problem.inputSize
    outputSize := problem.outputSize }

namespace SearchProblem

def IsTotal (problem : SearchProblem) : Prop :=
  ∀ input, problem.validInput input →
    ∃ output, problem.isSolution input output

def IsPolynomiallyBalanced (problem : SearchProblem) : Prop :=
  ∃ coefficient exponent : ℕ,
    ∀ input output, problem.validInput input →
      problem.isSolution input output →
        problem.outputSize input output ≤
          coefficient * (problem.inputSize input + 1) ^ exponent

end SearchProblem

/-- Input to the solution-decoding part of a search reduction. -/
abbrev ReductionDecodingInput
    (source target : SearchProblem)
    (mapInput : source.Input → target.Input) :=
  Σ input : source.Input, target.Output (mapInput input)

/-- Audited/instrumented polynomial many-one reduction between dependent
search problems.

Both maps have concrete `CostM` implementations.  This legacy layer is useful
for compositional accounting, but it is not instruction-enforced: use
`FixedEncodingPolynomialSearchReduction` for complexity-class definitions.
The mapped instance size is polynomially bounded, and every target solution
decodes to a source solution. -/
structure PolynomialSearchReduction
    (source target : SearchProblem) where
  mapInput : source.Input → target.Input
  mapOutput : (input : source.Input) →
    target.Output (mapInput input) → source.Output input
  maps_valid : ∀ input, source.validInput input →
    target.validInput (mapInput input)
  preserves_solution : ∀ input targetOutput,
    source.validInput input →
    target.isSolution (mapInput input) targetOutput →
      source.isSolution input (mapOutput input targetOutput)
  inputImplementation : RAMCostedImplementation mapInput
  outputImplementation : RAMCostedImplementation
    (fun pair : ReductionDecodingInput source target mapInput =>
      mapOutput pair.1 pair.2)
  inputTime : inputImplementation.IsPolynomial source.inputSize
  outputTime : outputImplementation.IsPolynomial fun pair =>
    source.inputSize pair.1 + target.outputSize (mapInput pair.1) pair.2
  mappedSize : PolynomialCostBound source.inputSize fun input =>
    target.inputSize (mapInput input)

/-- Existence of an explicit polynomial search reduction. -/
def SearchReducesTo (source target : SearchProblem) : Prop :=
  Nonempty (PolynomialSearchReduction source target)

/-! ## Instruction-enforced, fixed-representation search reductions -/

/-- Polynomial search reduction whose two algorithms are finite strict-RAM
programs and whose four representations are fixed outside the witness.

The decoding program receives the canonical length-prefixed dependent pair
`⟨source input, target solution⟩`.  In particular, it cannot select a custom
pair decoder that performs the reduction for free. -/
structure FixedEncodingPolynomialSearchReduction
    (source target : SearchProblem)
    (sourceInputEncoding : UnitCostRAM.Encoding source.Input)
    (sourceOutputEncoding : UnitCostRAM.DependentEncoding source.Output)
    (targetInputEncoding : UnitCostRAM.Encoding target.Input)
    (targetOutputEncoding : UnitCostRAM.DependentEncoding target.Output) where
  mapInput : source.Input → target.Input
  mapOutput : (input : source.Input) →
    target.Output (mapInput input) → source.Output input
  maps_valid : ∀ input, source.validInput input →
    target.validInput (mapInput input)
  preserves_solution : ∀ input targetOutput,
    source.validInput input →
    target.isSolution (mapInput input) targetOutput →
      source.isSolution input (mapOutput input targetOutput)
  inputProgram : StrictRAMComputableInPolyTime
    sourceInputEncoding
    (UnitCostRAM.Encoding.dependent targetInputEncoding)
    mapInput
  outputProgram : StrictRAMComputableInPolyTime
    (UnitCostRAM.Encoding.sigma sourceInputEncoding
      (targetOutputEncoding.comap mapInput))
    (sourceOutputEncoding.comap
      (fun pair : Σ input, target.Output (mapInput input) => pair.1))
    (fun pair : Σ input, target.Output (mapInput input) =>
      mapOutput pair.1 pair.2)
  /-- The target representation produced by the input map has polynomial word
  length in the fixed source representation.  It is stated explicitly because
  polynomial-time closure under composition needs an intermediate-size bound,
  exactly as in the `ten-proofs/GapCVP.lean` architecture. -/
  mappedSize : UnitCostRAM.IsPolyBound sourceInputEncoding.size fun input =>
    targetInputEncoding.size (mapInput input)

namespace FixedEncodingPolynomialSearchReduction

/-- The first stage emits exactly the target problem's canonical input words.
They may therefore be passed directly to a target strict-RAM solver; no
unaccounted decode/re-encode adapter is required between the two programs. -/
theorem inputProgram_outputs_canonical
    {source target : SearchProblem}
    {sourceInputEncoding : UnitCostRAM.Encoding source.Input}
    {sourceOutputEncoding : UnitCostRAM.DependentEncoding source.Output}
    {targetInputEncoding : UnitCostRAM.Encoding target.Input}
    {targetOutputEncoding : UnitCostRAM.DependentEncoding target.Output}
    (reduction : FixedEncodingPolynomialSearchReduction source target
      sourceInputEncoding sourceOutputEncoding
      targetInputEncoding targetOutputEncoding)
    (input : source.Input) :
    ∃ finalState,
      (UnitCostRAM.run
          (UnitCostRAM.closedEnvironment fun _ => false)
          reduction.inputProgram.program
          (reduction.inputProgram.fuel input)
          (sourceInputEncoding.encode input)).ret =
        .halted (targetInputEncoding.encode (reduction.mapInput input))
          finalState := by
  simpa [UnitCostRAM.Encoding.dependent] using
    reduction.inputProgram.correct input

/-- The decoding stage likewise emits exactly the canonical source-solution
encoding.  This is the operational normalization needed to compose a chain of
strict search reductions. -/
theorem outputProgram_outputs_canonical
    {source target : SearchProblem}
    {sourceInputEncoding : UnitCostRAM.Encoding source.Input}
    {sourceOutputEncoding : UnitCostRAM.DependentEncoding source.Output}
    {targetInputEncoding : UnitCostRAM.Encoding target.Input}
    {targetOutputEncoding : UnitCostRAM.DependentEncoding target.Output}
    (reduction : FixedEncodingPolynomialSearchReduction source target
      sourceInputEncoding sourceOutputEncoding
      targetInputEncoding targetOutputEncoding)
    (pair : Σ input, target.Output (reduction.mapInput input)) :
    ∃ finalState,
      (UnitCostRAM.run
          (UnitCostRAM.closedEnvironment fun _ => false)
          reduction.outputProgram.program
          (reduction.outputProgram.fuel pair)
          ((UnitCostRAM.Encoding.sigma sourceInputEncoding
            (targetOutputEncoding.comap reduction.mapInput)).encode pair)).ret =
        .halted
          (sourceOutputEncoding.encode pair.1
            (reduction.mapOutput pair.1 pair.2))
          finalState := by
  simpa [UnitCostRAM.DependentEncoding.comap] using
    reduction.outputProgram.correct pair

end FixedEncodingPolynomialSearchReduction

/-- Existence of a fixed-representation, instruction-enforced polynomial
search reduction. -/
def FixedEncodingSearchReducesTo
    (source target : SearchProblem)
    (sourceInputEncoding : UnitCostRAM.Encoding source.Input)
    (sourceOutputEncoding : UnitCostRAM.DependentEncoding source.Output)
    (targetInputEncoding : UnitCostRAM.Encoding target.Input)
    (targetOutputEncoding : UnitCostRAM.DependentEncoding target.Output) : Prop :=
  Nonempty
    (FixedEncodingPolynomialSearchReduction source target
      sourceInputEncoding sourceOutputEncoding
      targetInputEncoding targetOutputEncoding)

/-- Concise strict-reduction predicate for problems that already carry their
fixed encodings. -/
def FixedSearchReducesTo
    (source target : FixedEncodingSearchProblem) : Prop :=
  FixedEncodingSearchReducesTo
    source.toSearchProblem target.toSearchProblem
    source.inputEncoding source.outputEncoding
    target.inputEncoding target.outputEncoding

end EconCSBench
end OpenProblem
end EconCSLib
